debug.gemspec
This gem exposes no executables.
=> gemspec: Explicitly empty executables list

ext/debug/extconf.rb, lib/debug/session.rb
This is to solve #3 by using [Rubygems' recommended approach](https://guides.rubygems.org/gems-with-extensions) to name/load this gem's c extension.
Summary of the commit:
1. Use `require` instead of `require_relative` to load the extension file.
2. Use the recommended way to name the extension in `extconf.rb`.
According to Rubygems' guideline, we should use `"debug/debug"` when calling `create_makefile`. Then we can use `require "debug/debug" to require the extension.
https://guides.rubygems.org/gems-with-extensions/#extension-naming
Currently, `create_makefile "debug"` means that the require path would be `require "debug"`, which confuses Ruby. As a result it'd always load `debug.rb` instead of the compiled extension.
**Test Command**
```
$ gem build debug.gemspec; gem install --local …
```
=> Use recommended way to name/load c extension

README.md, lib/debug/session.rb
Closes #6
```
❯ exe/rdbg foo.rb
[1, 1] in foo.rb
=>    1| puts(1)
=>#0    <main> at foo.rb:1
(rdbg) q
Really quit? [Y/n] Y
```
```
❯ exe/rdbg foo.rb
[1, 1] in foo.rb
=>    1| puts(1)
=>#0    <main> at foo.rb:1
(rdbg) quit
Really quit? [Y/n] Y
```
```
❯ exe/rdbg foo.rb
[1, 1] in foo.rb
=>    1| puts(1)
=>#0    <main> at foo.rb:1
(rdbg) q!
```
```
❯ exe/rdbg foo.rb
[1, 1] in foo.rb
=>    1| puts(1)
=>#0    <main> at foo.rb:1
(rdbg) quit!
```
```
❯ exe/rdbg foo.rb
[1, 1] in foo.rb
=>    1| puts(1)
=>#0    <main> at foo.rb:1
(rdbg) kill
Really kill? [Y/n] Y
```
```
❯ exe/rdbg foo.rb
[1, 1] in foo.rb
=>    1| puts(1)
=>#0    <main> at foo.rb:1
(rdbg) kill!
```
=> Refine exit commands

.gitignore
Currently, running `rake` or `rake compile` would generate `lib/debug/debug.bundle`.
Those files are generated by the extension complication and should not be committed into the codebase.
=> Ignore all bundle files

Gemfile
```
$ bundle exec rake
Failed to remove lib/debug/debug.bundle: wrong number of arguments (given 2, expected 1)
Failed to remove tmp: wrong number of arguments (given 2, expected 1)
rake aborted!
ArgumentError: wrong number of arguments (given 2, expected 1)
~/.gem/ruby/3.0.1/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
```
=> Update rake for Ruby 3.0 compatibility

lib/debug/frame_info.rb, lib/debug/session.rb, lib/debug/thread_client.rb
I know it's probably risky to do such refactoring without test cases but I couldn't help it 😄
Besides reducing the length of `thread_client.rb`, once we move frame string computation out of `ThreadClient`, we can eliminate many method parameters and reduce variable declarations.
(This is a proof of concept so I don't extract all the methods yet.)
=> Extract frame info computation out of TheadClient

lib/debug/session.rb
Fixes scenarios where session isn't started immediately.
require 'debug/session'
DEBUGGER__.console # raises NameError
=> Require console for UI_Console

lib/debug/frame_info.rb, lib/debug/thread_client.rb
- Extract some remaining frame computation from `ThreadClient` to `FrameInfo`.
- Remove unnecessary local variable assignments.
- Encapsulate several `FrameInfo` helper methods.
It'll be easier to review by commits. And same as #17, this PR doesn't introduce any behavioral change.
=> Follow up refactoring of #17

lib/debug/breakpoint.rb, lib/debug/session.rb
fix https://github.com/ruby/debug/issues/27
=> fix bug for "catch" command

lib/debug/thread_client.rb
Since `IRB` already has coloring helpers, I figure it'd better to use it instead of having this library's own one? If this is a reasonable approach, I can use the same helper to colorize the backtrace in another PR. Some notes:
1. Because this library will be Ruby `3.1`'s default, the `irb` should always have the coloring feature (added after `2.7`).
2. I assume that if the debugger can start, the frame's source file must be "complete". So I choose the default complete mode.
Result:
=> Use IRB's coloring helper to colorize source

lib/debug/frame_info.rb, lib/debug/thread_client.rb
I figure the call identifier should use the same color as the identifier token (e.g. method name), so I used blue for it. The other 2 components' colors were arbitrarily picked.
=> Colorize frame info with irb coloring helper

lib/debug/frame_info.rb, lib/debug/thread_client.rb
**Before**
```
#5    Foo#second_call(num=20) at target.rb:7
#6    first_call at target.rb:3
```
**After**
```
#5    Foo#second_call(num=20) at target.rb:7
#6    Foo#first_call at target.rb:3
```
This change simplifies implementation and makes the trace look better imo.
- Because `FrameInfo` doesn't handle data representation, it shouldn't contain any colorization logic. Which means the `call_identifier_str` now needs to be assembled in `ThreadClient`.
=> Colorize parameters

lib/debug/thread_client.rb
it's still a bit dazzling with a white bright background, but I think we won't be able to find a perfect color without adding a new color code.
=> Change frame location's color to green

lib/debug/frame_info.rb
We should clean up error result (`nil`) from the return value of `FrameInfo#parameters_info`. This is to fix this error:
```
(rdbg) bt
["/Users/st0012/projects/debug/lib/debug/thread_client.rb",
559,
#<NoMethodError: undefined method `[]' for nil:NilClass>,
["/Users/st0012/projects/debug/lib/debug/thread_client.rb:31:in `block in assemble_arguments'",
"/Users/st0012/projects/debug/lib/debug/thread_client.rb:30:in `map'",
"/Users/st0012/projects/debug/lib/debug/thread_client.rb:30:in `assemble_arguments'",
"/Users/st0012/projects/debug/lib/debug/thread_client.rb:50:in `default_frame_formatter'",
```
=> Result of FrameInfo#parameters_info shouldn't contain nil

Gemfile, bin/test-unit.rb, test/debug/break_test.rb, test/debug/next_test.rb, test/debug/step_test.rb, test/support/test_case.rb, test/support/utils.rb
This is the trial implementation of test code for debugger by using multi processes.
- Use module PTY to create pseudo terminals for debugger.
- Write test codes for `next` and `step` and `break`
```
$ ruby bin/test-unit.rb
$ ruby bin/test-unit.rb debug/break_test.rb
```
[![Image from Gyazo](https://i.gyazo.com/2bbe47cb20b9a49f48a0c6c0ad146d9e.gif)](https://gyazo.com/2bbe47cb20b9a49f48a0c6c0ad146d9e)
The following test code is based on [byebug ](https://github.com/deivid-rodriguez/byebug)project
=> Trial implementation of test code for debbuger -multi processes

test/support/utils.rb
few things I found when writing tests for the `backtrace` command:
- there's a typo: `psuedo` should be `pseudo`.
- the pseudo terminal should return full sentence and line number extraction should only happen in the matcher.
- the pseudo terminal should also disable coloring for better text matching.
=> Improve test setup

test/debug/watch_test.rb
I found several things when playing with the `watch` command:
- It mainly uses `line` events to detect the change instead of the `return` events (I'm not sure why though). This causes the program to always stop a line after the change. So in tests we need to add an extra line after the changed line. Otherwise it doesn't stop.
- It always evaluates the expression from top-level scope. So it's not able to track an instance variable inside an object like `watch @name` and users need to use `watch obj.name` instead. I think we should improve this.
But before we do anything on it, we should have some test cases to check its behavior. That's why I open this PR.
=> Add tests for watch command

lib/debug/source_repository.rb
Calling `iseq.absolute_path` might return nil.
Seems to be similar to #10. 
```
#<Thread:0x0000aaaaf9db75a0 /usr/local/bundle/gems/debug-1.0.0.beta4/lib/debug/session.rb:68 run> terminated with exception (report_on_exception is true):
4: from /usr/local/bundle/gems/debug-1.0.0.beta4/lib/debug/session.rb:78:in `block in initialize'
3: from /usr/local/bundle/gems/debug-1.0.0.beta4/lib/debug/session.rb:826:in `on_load'
2: from /usr/local/bundle/gems/debug-1.0.0.beta4/lib/debug/source_repository.rb:14:in `add'
1: from /usr/local/bundle/gems/debug-1.0.0.beta4/lib/debug/source_repository.rb:20:in `add_path'
/usr/local/bundle/gems/debug-1.0.0.beta4/lib/debug/source_repository.rb:20:in `file?': no implicit conversion of nil into String (TypeError)
```
I …
=> Only call File.file? when path present

lib/debug/config.rb
Currently the `rdbg` command only supports `--help` option but not the shorter `-h`:
```
❯ exe/rdbg -h
/Users/st0012/projects/debug/lib/debug/config.rb:153:in `parse_argv': missing argument: -h (OptionParser::MissingArgument)
from exe/rdbg:5:in `<main>'
```
This is surprising when compared with the `ruby` or `irb` commands:
```
❯ irb -h
Usage:  irb.rb [options] [programfile] [arguments]
-f                Suppress read of ~/.irbrc
-v, --version     Print the version of irb
-h, --help        Print help
--                Separate options of irb from the list of command-line args
```
So this PR adds the support to make it align with other tools:
```
❯ exe/rdbg -h
exe/rdbg [options] -- [debuggee options]
Debug console mode:
-h, --help                       Print help
-n, --nonstop …
```
=> Support -h option

README.md
This change makes the badge go non-green only when the default branch ("master") has a failing CI. And the link now focuses the build on that branch.
=> README: Build status Badge only about "master"

test/debug/break_test.rb, test/debug/next_test.rb, test/debug/step_test.rb, test/support/utils.rb
Displaying line numbers in test programs is easy to write test code.
This method is based on [byebug ](https://github.com/deivid-rodriguez/byebug)project
=> display line numbers for test programs

lib/debug/breakpoint.rb, lib/debug/source_repository.rb, test/debug/breakpoint_test.rb
There are several errors fixed in this PR. The first triggers this:
```
/Users/st0012/projects/debug/lib/debug/source_repository.rb:42:in `read': no implicit conversion of nil into String (TypeError)
```
The 2nd and 3rd issue are explained in the commit message and comments.
=> Fix MethodBreakpoint

Gemfile, debug.gemspec
Ruby 2.x's irb doesn't have the `irb/color_printer` that the debugger relies on. So users of those versions need to manually add `irb` to their gemfiles. I think we can save them the work by adding `irb` as this project's dependency.
CI didn't fail because we have `irb` in our gemfile as a development dependency.
=> Add irb as dependency for 2.x Ruby users

.gitignore
`rbenv` generates the `.ruby-version` file when switching between Ruby versions inside a repo. We should not allow committing this file into the project.
=> Ignore rbenv's .ruby-version file

test/debug/bp_test.rb, test/support/utils.rb
Test programs without line numbers will fail with a line-numbered version. So developers only needs to copy & paste them.
Example:
```
Error: test_breakpoint_execute_command_argument_correctly(DEBUGGER__::BindingBPWithCommandTest):
RuntimeError: line numbers are required in test script. please update the script with:
1| class Foo
2|   def bar
3|     binding.bp(command: "continue")
4|     baz
5|   end
6|
7|   def baz
8|     binding.bp
9|   end
10| end
11|
12| Foo.new.bar
```
After this PR, the workflow would be:
1. Write plain Ruby script.
2. Run tests (fail for test/program logic).
3. Fix the test/debugger.
4. Run tests (fail for missing line numbers).
5. Fix the scripts by copy & paste.
=> Require & generate line numbers for test scripts

README.md, lib/debug/breakpoint.rb, lib/debug/session.rb, lib/debug/thread_client.rb, test/debug/watch_test.rb
Based on the discussion in https://github.com/ruby/debug/issues/49, having `WatchExprBreakpoint` for watch all expression changes costs too much on performance but provide limited benefit to the users. But because watching instance variables for state changes is still valuable for debugging, we're going to support this particular case.
So in this PR, I made these changes:
- Replace `WatchExprBreakpoint` with `WatchIVarBreakpoint`.
- `watch expr` is no longer supported.
- `watch @ivar` is more accurate and cheaper.
---
Currently, when watching instance variables, the breakpoint isn't aware of the instance/class it's tracking on. So it could incorrectly track instance variable change (with the same name) in a different class. 
For example, if you debug this script:
```ruby
class Student …
```
=> Replace WatchExprBreakpoint with WatchIVarBreakpoint

lib/debug/test_console.rb, test/support/utils.rb
- rename 'lines' to 'backlog'
- use "last_backlog" instead of "internal_info[:backlog]"
- define create_message method to output backlog when assertion failed
=> improve test framework in backlog

lib/debug/session.rb
swap locations of variables "bp" and "i"
```shell
[2, 11] in target.rb
2|   class Bar
3|     def self.a
4|       "hello"
5|     end
6|     def b(n)
=>    7|       2.times do
8|         n
9|       end
10|     end
11|   end
=>#0	Foo::Bar#b(n=1) at target.rb:7
#1	<module:Foo> at target.rb:19
#2	<main> at target.rb:1
Stop by # BP - Check  n==1 0
```
```shell
[2, 11] in target.rb
2|   class Bar
3|     def self.a
4|       "hello"
5|     end
6|     def b(n)
=>    7|       2.times do
8|         n
9|       end
10|     end
11|   end
=>#0	Foo::Bar#b(n=1) at target.rb:7
#1	<module:Foo> at target.rb:19
#2	<main> at target.rb:1
Stop by #0  BP - Check  n == 1
```
=> Fix appearance of "Stop by~"

README.md, lib/debug/frame_info.rb, lib/debug/thread_client.rb, test/debug/backtrace_test.rb
=> Capture block label with regexp 

README.md, misc/README.md.erb
It's kinda hard to distinguish different usage options in a large code block containing both text, Ruby code and shell commands. I think it'd be easier to read if we give different options a header.
=> Use markdown header for usage options

lib/debug/color.rb, test/debug/info_test.rb
Exceptions raised when inspecting frame variables cause the debugger to
exit with the original Exception.
Instead, note to the user that an exception was rescued and any possible
result of `#to_s` on the failing object.
Closes #45
=> Rescue exceptions raised when inspecting objects

test/support/utils.rb
When writing tests, sometimes we may test the script manually. But currently this could take a few steps:
1. Copy the test program into a file, say `target.rb`
2. Remove all the line numbers.
3. Run `exe/rdbg -e target.rb` from the terminal.
And whenever we change the script or switched to another test case, we need to go through these steps again. 
So in the PR, I introduced a new helper called `_start_manual_debug_session(program)`. You can place it in any test case:
```ruby
def program
end
def test_something_about_debugger
_start_manual_debug_session(program) # just add this line
debug_code(program) do
end
end
```
And then run the test case as you usually do, it'll enter a debug session with your test script 😄 
(btw, the remote debugging session is pretty neat. I love it 😍 )
=> Add a helper to start debug session with the test program

test/support/utils.rb
Change `"#{fail_msg}\n[DEBUG SESSION LOG]\n" + @backlog.map { |l| "> #{l}" }.join` to `"#{fail_msg}\n[DEBUG SESSION LOG]\n> " + @backlog.join('> ')`
```ruby
require 'benchmark'
@backlog = ["[1, 10] in /var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/debugger20210616-11566-40d1gt.rb\r\n", "=>    1| class TestException < StandardError; end\r\n", "      2| \r\n", "      3| module Foo\r\n", "      4|   class TestException < StandardError; end\r\n", "      5| \r\n", "      6|   def self.raised_exception\r\n", "      7|     raise TestException\r\n", "      8|   end\r\n", "      9| end\r\n", "     10| \r\n", "=>#0\t<class:TestException> at /var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/debugger20210616-11566-40d1gt.rb:1\r\n", "  #1\t<main> at …
```
=> Improve the algorithm in create message method

test/support/utils.rb, test/test_utils_test.rb
Currently, tests would still pass if the test triggers a debugger error, like:
This PR fixes from 2 directions:
1. When seeing `ERROR REPL` message, the test framework should raise error.
2. If for any reason, the test queue isn't empty after the terminal is finished, it should fail the test.
=> Improve test framework's handling on debugger exceptions & early exits

test/support/assertions.rb, test/support/test_case.rb, test/support/utils.rb
This is an another approach to improve assert methods.
- use assert_block to output clearer fail logs
- override "to_s" method in "assert_block" method
- We don't have to modify `assert_block` in `test-unit`.
=> Improve assert methods [2nd pattern]

lib/debug/session.rb, test/debug/trace_test.rb, test/support/assertions.rb
This PR also adds a new `assert_no_line_text` test assertion helper.
=> Add trace tests

lib/debug/session.rb, lib/debug/thread_client.rb
Currently, `Session` handles breakpoints in 3 different ways:
- `watch` breakpoints - enqueued as an `eval` thread client event. 
- `method` breakpoints - enqueued as a `breakpoint` thread client event.
- other breakpoints - initialized and registered directly without being enqueued.
This PR makes `Session` handle watch breakpoints similar to method breakpoints as:
- `watch`/`method` breakpoints - enqueued as a `breakpoint` thread client event.
- other breakpoints - initialized and registered directly without being enqueued.
This refactor will make future changes on breakpoints easier (for example, prevent duplicated breakpoints).
**It doesn't change any output or functionality**
**Before**
**After**
=> Unify watch & method breakpoint handling

test/debug/trace_test.rb, test/support/utils.rb
`Regexp.union` doesn't create `AND` combination but `OR` combination, which makes the tests inaccurate.
=> Fix trace tests

lib/debug/frame_info.rb
Because https://github.com/ruby/debug/commit/c6cf3b202680f36e133660fe37712cbeb7349f23 changed the lib path (`lib` -> `lib/debug`), the `require "debug/debug"` inside `frame_info.rb` does not work anymore.
```
❯ exe/rdbg -e 'c' target.rb
13: from /Users/st0012/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
12: from /Users/st0012/.rbenv/versions/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
11: from /Users/st0012/projects/debug/lib/debug/run.rb:1:in `<top (required)>'
10: from /Users/st0012/projects/debug/lib/debug/run.rb:1:in `require_relative'
9: from /Users/st0012/projects/debug/lib/debug/console.rb:1:in `<top (required)>'
8: from /Users/st0012/projects/debug/lib/debug/console.rb:1:in …
```
=> Fix rdbg executable

test/support/utils.rb
@st0012 pointed out the problem that test framework doesn't support multiple assert methods after one command.
https://github.com/ruby/debug/pull/103#discussion_r656355053
This PR will fix it.
=> Support multiple assertions after one command

lib/debug/thread_client.rb, test/debug/eval_test.rb
For `[:eval, :call]` events (`eval` and `irb` commands), `ThreadClient` evaluates the source twice:
https://github.com/ruby/debug/blob/fbe17413d5e7c33a51502c2ca1763ed3bcae4ed0/lib/debug/thread_client.rb#L480-L484
https://github.com/ruby/debug/blob/fbe17413d5e7c33a51502c2ca1763ed3bcae4ed0/lib/debug/thread_client.rb#L494-L495
This is unnecessary and can cause some issues (like it'll trigger 2 `irb` sessions).
=> Remove duplicated evaluation

test/debug/session_test.rb, test/support/utils.rb
I implement the test framework for remote debugger.
- Assign the argument `remote: false` in `debug_code` method when using `require "debug/run"` or `DEBUGGER__.console`.
- Test for remote and local are in each method by one. That's why if first test(local) failed, second test(remote) won't work.
- Test for local test will be executed first, and Test for remote(UNIX domain socket mode and TCP/IP mode) will be executed next.
=> Test for remote debugger

test/support/utils.rb
This PR will fix `Errno::EMFILE: Too many open files - fork failed`, not to fix issue #118 completely because it won't fix `Timeout Error`.
=> fix part of #118

test/assertion_helper_test.rb, test/debug/trace_test.rb, test/support/assertions.rb, test/support/utils.rb
As suggested in https://github.com/ruby/debug/pull/104#issuecomment-863797701
=> Allow assert_line_text helper to take array expectation

lib/debug/config.rb
Because all strings in `config.rb` are now frozen, passing the commands option causes:
```
❯ exe/rdbg -e "c" target.rb
/Users/st0012/projects/debug/lib/debug/config.rb:96:in `block (2 levels) in parse_argv': can't modify frozen String: "" (FrozenError)
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/optparse.rb:1623:in `block in parse_in_order'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/optparse.rb:1577:in `catch'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/optparse.rb:1577:in `parse_in_order'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/optparse.rb:1571:in `order!'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/optparse.rb:1668:in `permute!'
from /Users/st0012/.rbenv/versions/3.0.1/lib/ruby/3.0.0/optparse.rb:1693:in `parse!'
from …
```
=> Avoid mutating the commands string

test/debug/break_test.rb, test/debug/catch_test.rb
Since the test framework can now handle implicit exit, the old workaround can go.
=> Remove old workaround on tests

README.md, misc/README.md.erb
Write how to use with bundler in README.
As far as I know, "1.0.0.a" means "--pre" on Gemfile.
https://guides.rubygems.org/patterns/#pessimistic-version-constraint
I've tested the following codes.
Gemfile
```
source "https://rubygems.org"
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "debug", ">= 1.0.0.beta"
```
target.rb
```ruby
ENV['RUBY_DEBUG_NONSTOP'] = 'true'
require 'debug/run'
class Foo
def foo
string = "foo!!!"
binding.bp # or binding.debug
string
end
end
p Foo.new.foo
```
```
$ rdbg -c bundle exec ruby target.rb
```
=> Add using with bundler in README

lib/debug/client.rb, test/support/utils.rb
* setup_terminal -> debug_on_local/unix_domain_socket/tcpip
* remote not-needed `@mutex`
* rename `create_pseudo_terminal` to `run_test_scenario`
* kill/close debug console process and fds
* change prompt on remote debugging (rdb) -> (rdbg:remote)
=> clearnup `debug_code` method

lib/debug/server.rb, test/support/utils.rb
The reason of timeout error is seeing different Queue in readline
method accidentally. To fix it, setup Queues at the beggining of
accept block.
In addition, use rdbg on UNIX domain socket.
=> fix remote timeout error.

test/support/utils.rb
Now, logs of `remote debugee` doesn't show in failure message. This PR fix it.
```shell
Failure: test_foo(DEBUGGER__::FooTest):
TIMEOUT ERROR (10 sec) on UNIX DOMAIN SOCKET mode
[DEBUGGER SESSION LOG]
> [1, 9] in /var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/debugger20210706-45047-efy1kk.rb
> =>    1| module Foo
>       2|   class Bar
>       3|     def self.a
>       4|       p "hello"
>       5|     end
>       6|   end
>       7|   Bar.a
>       8|   bar = Bar.new
>       9| end
> =>#0	<main> at /var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/debugger20210706-45047-efy1kk.rb:1
> s
>
> (rdbg:remote) s
[1, 9] in /var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/debugger20210706-45047-efy1kk.rb
>       1| module Foo
> =>    2|   class Bar
>       3|     def self.a
>       4|       p …
```
=> Improve debug log -add remote debuggee backlog

test/assertion_helper_test.rb, test/support/test_case.rb, test/support/utils.rb, test/test_utils_test.rb
Currently, `check_line_num` method will be executed after the test finished. The line numbers should be checked first because `test/assertion_helper_test.rb` and `test/test_utils_test.rb` will exit before `check_line_num` method is executed. This PR will fix it.
I also changed constant variable(`DEBUG_MODE`) to ENV variable(`ENV["RUBY_DEBUG_TEST_DEBUG_MODE"]`).
=> Improve test framework

lib/debug/breakpoint.rb, lib/debug/session.rb, test/debug/bp_test.rb, test/debug/break_test.rb, test/debug/catch_test.rb
The debugger currently shows a warning message for duplicated breakpoints and doesn't add it to the breakpoints list. But line or catch breakpoints would still be activated and stop the program.
To fix this issue, we need to disable duplicated breakpoints. However, `binding.bp` also uses line breakpoints with a fixed internal location, simply excluding duplicated breakpoints will break it.
So the solution requires 2 checks:
1. Check if the breakpoint is duplicated by key.
2. Check if it's a normal breakpoint (e.g. added by the `break` command) instead of a `oneshot` (binding.bp or DEBUGGER__.console) breakpoint.
If both are satisfied, the debugger should warn the user and disable the breakpoint.
It also fixes the issue that multiple `binding.bp` raises duplicated breakpoints warning, …
=> Make sure duplicated breakpoint is disabled

CONTRIBUTING.md, bin/gentest, test/tool/test_builder.rb
https://user-images.githubusercontent.com/59436572/122718083-74730b00-d2a7-11eb-9db2-c50a117175ce.mov
This is a test generator to make it easier to write tests.
There is a test generator in `debug.rb` project to make it easier to write tests.
This section shows you how to create test file by test generator. For more advanced informations on creating tests, please take a look at [gentest options](#gentest-options). (You can also check by `$bin/gentest -h`)
Let's say, we created `target.rb` which is located in top level directory of debugger.
```ruby
module Foo
class Bar
def self.a
"hello"
end
end
Bar.a
bar = Bar.new
end
```
```shell
$ bin/gentest target.rb
```
```shell
$ bin/gentest target.rb
[1, 9] in ~/workspace/debug/target.rb
=>    1| module Foo
2|   class Bar
3|     def self.a
4| …
```
=> test builder

test/debug/break_test.rb, test/debug/catch_test.rb, test/debug/watch_test.rb
This should catch issues similar to what's mentioned in https://github.com/ruby/debug/issues/139#issuecomment-875304029 in the future.
=> Use full bp message as test expectation

test/tool/test_builder.rb
I implemented three points.
test_foo
test_1625738032
```ruby
def test_1625737361
debug_code(program) do
type 's'
assert_line_num 2
assert_line_text([
/\[1, 10\] in .*/,
/      1\| module Foo/,
/=>    2\|   class Bar/,
/      3\|     def self\.a/,
/      4\|       "hello"/,
/      5\|     end/,
/      6\| /,
/      7\|     def b_123\(n\)/,
/      8\|       2\.times do/,
/      9\|         n/,
/     10\|       end/,
/=>\#0\t<module:Foo> at .*/,
/  \#1\t<main> at .*/
])
type 'n'
assert_line_num 3
assert_line_text([
/\[1, 10\] in .*/,
/      1\| module Foo/,
/      2\|   class Bar/,
/=>    3\|     def self\.a/,
/      4\|       "hello"/,
/      5\|     end/,
/      6\| /,
/      7\|     def b_123\(n\)/,
/      8\|       2\.times do/,
/      9\|         n/,
/     10\|       end/, …
```
=> Improve test builder

lib/debug/thread_client.rb, test/support/utils.rb
1. The exception detection introduced in https://github.com/ruby/debug/pull/150 doesn't apply to GNU/Linux platforms. A test fails after the detection is added but it only presents on some platforms (like macOS)
```
✦ ❯ ruby test/debug/catch_test.rb -n /reject/
Loaded suite test/debug/catch_test
Started
E
=========================================================================================================================================================================================================================
Error: test_debugger_rejects_duplicated_catch_bp(DEBUGGER__::BasicCatchTest):
Traceback (most recent call last):d because of:
1: from /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debugger20210709-94267-3vfzfn.rb:4:in `<main>' …
```
=> Fix debugger exception detection

README.md, misc/README.md.erb
Document use of `binding.bp` to setup breakpoints inside application,
without immediately invoking the debugger console.
=> Add `binding.bp` to README

test/tool/test_builder.rb
Current test builder can't get the ask pattern like this. This PR fix it.
```shell
$ bin/gentest target.rb
DEBUGGER: Session start (pid: 95363)
[1, 4] in ~/workspace/debug/target.rb
=>    1| a = 1
2| b = 2
3| c = 3
4| d = 4
=>#0	<main> at ~/workspace/debug/target.rb:1
INTERNAL_INFO: {"location":"~/workspace/debug/target.rb:1","line":1}
(rdbg)b 2
b 2
#0  BP - Line  /Users/naotto/workspace/debug/target.rb:2 (line)
INTERNAL_INFO: {"location":"~/workspace/debug/target.rb:1","line":1}
(rdbg)del
del
#0  BP - Line  /Users/naotto/workspace/debug/target.rb:2 (line)
```
=> Make sure to match ask pattern in test_builder

lib/debug/color.rb
Reproduction Script:
```ruby
class Foo
def initialize
@string = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
end
end
f = Foo.new
binding.bp
```
```
$ exe/rdbg -e 'c ;; info ;; q!' target.rb
```
**Before**
**After**
This only happens with coloring enabled, so it's not catchable by tests.
=> color_pp's default width shouldn't be nil

README.md, lib/debug/breakpoint.rb, lib/debug/session.rb, test/debug/break_test.rb
To recognize Ruby's if/do expression, change the keyword
`if` -> `if:` and introduce `do:`.
=> add 'break ... do: expression'

test/color_test.rb
```shell
$ ruby test/color_test.rb
Loaded suite test/color_test
Started
.test/color_test.rb:103: warning: redefining constant Struct::SESSION
...
Finished in 0.0054 seconds.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
4 tests, 14 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
=> Solve the `warning: redefining constant Struct::SESSION`

README.md, lib/debug/color.rb, lib/debug/session.rb, lib/debug/thread_client.rb, test/debug/info_test.rb
* `info` for locals, ivars and constants (only self)
* `info locals`, `ivars`, `globals`: show variables
* `info constants`: show constant variables which are accessible from this context.
* `info ... </pattern/>` support filtering
* `info` should puts 1 line per 1 value.
=> Info variants

test/assertion_helper_test.rb
Add `remote: false` in assertion_helper test because assertion_helper_test is unit tests
=> add remote: false in assertion_helper test

test/tool/test_builder.rb
Currently, if we input the class name without `test`, the result of class name doesn't include `test`. I fixed it by https://github.com/ruby/debug/pull/190/files#diff-696c1d15a0b4a6b6059b82ff19a13d0aafa2f5b00c87a0b5436b8713821d9f2aR16.
```shell
$ bin/gentest target.rb -c bar
DEBUGGER: Session start (pid: 99572)
[1, 10] in ~/workspace/debug/target.rb
=>    1| module Foo
2|   class Bar
3|     def self.a
4|       "hello"
5|     end
6|
7|     def b(n)
8|       2.times do
9|         n
10|       end
=>#0	<main> at ~/workspace/debug/target.rb:1
INTERNAL_INFO: {"location":"~/workspace/debug/target.rb:1","line":1}
(rdbg)s
s
[1, 10] in ~/workspace/debug/target.rb
1| module Foo
=>    2|   class Bar
3|     def self.a
4|       "hello"
5|     end
6|
7|     def b(n)
8|       2.times do
9|         n
10| …
```
=> Test builder should add "Test" if the string "test" is not included in method name

test/assertion_helper_test.rb, test/support/assertions.rb
The `(?-mix:~` is hard to make sense in failure message. I add `inspect` method for human-readable object.
```shell
Failure: test_quit_quits_debugger_process_if_confirmed(DEBUGGER__::QuitTest):
Expected to include `(?-mix:Really quit\? \[Y\/n\]hoge)` in
(
Really quit? [Y/n] y
)
```
```shell
Failure: test_quit_quits_debugger_process_if_confirmed(DEBUGGER__::QuitTest):
Expected to include `/Really quit\? \[Y\/n\]hoge/` in
(
y
(rdbg) q
Really quit? [Y/n] y
)
```
=> Add inspect method for clearer failure messages

lib/debug/config.rb, lib/debug/session.rb, lib/debug/thread_client.rb, test/debug/config_test.rb
```
(rdbg) config set trace_alloc true
trace_alloc = true             # CONTROL: Keep allocation site and p, pp shows it (default: false)
(rdbg) n
[1, 4] in target.rb
1| a = Object.new
=>    2| p a
3|
4| __END__
=>#0    <main> at target.rb:2
(rdbg) p a
=> #<Object:0x00005564a2b4ebd0>
allocated at target.rb:1
```
=> new config `keep_alloc_site` to keep allocation site

lib/debug/thread_client.rb
- Similar methods are now closer together, for example `#to_s` is now next to `#inspect`.
- Command-specific methods are grouped by the command.
- Comments are added for different sections.
=> Document and reorganize ThreadClient

test/support/assertions.rb, test/support/utils.rb, test/test_utils_test.rb
These are example of test(debug) time for Github workflow.
Finished in 379.300202619 seconds.
https://github.com/ruby/debug/runs/3179106902
Finished in 199.289802343 seconds.
https://github.com/ruby/debug/runs/3179484608
- The all instance variables are stored as `Struct` class.
- Queue instance is created for each threads.
- That's why I don't use `test-unit`'s assert method under multi threads. As the alternative plan, I implemented as follows.
- If a test fail, the current thread will do nonlocal exits.
-  If a test succeeds, assert method doesn't do nothing and `assert true` will be run.
- I am concerned that the number of assert's is not accurate.
=> Implementation of Multi-thread in test framework

lib/debug/breakpoint.rb, test/debug/break_test.rb
The `**kw` would be considered as an Array in Ruby 2.6 and be passed to the method, which then cause argument error in methods like `Integer#times` or `Array#each`.
I spotted this issue in [this build](https://github.com/ruby/debug/pull/206/checks?check_run_id=3200344389)
```
> #<Thread:0x00005650511f61c8@/home/runner/work/debug/debug/lib/debug/session.rb:92 run> terminated with exception (report_on_exception is true):
> /home/runner/work/debug/debug/lib/debug/breakpoint.rb:401:in `each': wrong number of arguments (given 1, expected 0) (ArgumentError)
> 	from /home/runner/work/debug/debug/lib/debug/breakpoint.rb:401:in `block (2 levels) in override'
> 	from /home/runner/work/debug/debug/lib/debug/session.rb:200:in `ensure in session_server_main'
> 	from …
```
=> Fix overriden method's argument passing in Ruby 2.6

lib/debug/tracer.rb, test/debug/trace_test.rb
Methods with `...` parameter doesn't read any argument, so the tracer should just ignore it.
Currently the tracer doesn't handle this case:
```
❯ ruby -Ilib -r debug target.rb
DEBUGGER: Session start (pid: 54807)
[1, 7] in target.rb
=>    1| binding.b(do: "trace pass 1")
2|
3| def foo(...)
4|   block.call
5| end
6|
7| foo(1)
=>#0    <main> at target.rb:1
(rdbg:binding.break) trace pass 1
Enable PassTracer for 1 (enabled)
5: from target.rb:7:in `<main>'
4: from target.rb:4:in `foo'
3: from /Users/st0012/projects/debug/lib/debug/tracer.rb:142:in `block in setup'
2: from /Users/st0012/projects/debug/lib/debug/tracer.rb:142:in `each'
1: from /Users/st0012/projects/debug/lib/debug/tracer.rb:153:in `block (2 levels) in setup' …
```
=> Fix anonymous rest argument tracing

test/assertion_helper_test.rb, test/support/utils.rb, test/test_utils_test.rb
Users should be able to freely change their test script without the interruption of the line numbers until the script is confirmed working.
Only then should the test framework check the script's line numbers with a suggested change (if it doesn't have them yet).
This change will disable line number check on the test framework's tests because most of those cases are designed to fail. But the number check wasn't design for those tests anyway.
=> Only check line numbers after the test is finished

lib/debug/thread_client.rb
Printing full inspect result would make the tracing unusable in Rails apps because there are many big objects. 
If we want to let user know about the trace's object, a truncated result should do the work too.
**Before**
**After**
=> Truncate trace message

lib/debug/tracer.rb, test/debug/trace_test.rb
I spotted that the call tracer ignores the debugger's methods but not the methods from related libraries, like `irb` for coloring. So it looks like this:
This PR fixes the issue:
=> Call tracer should ignore calls made from the library it uses

debug.gemspec, lib/debug/console.rb, lib/debug/session.rb, test/support/utils.rb
reline 0.2.7 supports running on non-main thread so use it.
`rake test` fails so it is disabled on a test.
=> use reline

test/debug/config_test.rb, test/debug/record_test.rb, test/tool/test_builder.rb
@ko1 pointed out that the file generated by test builder doesn't display line number correctly. The reason is that counting the line number from index was wrong.
I also refactored the part.
=> 11c4907, 4788eb8
=> Modify the test builder so that the line numbers are displayed correctly in the generated file

lib/debug/tracer.rb, test/debug/trace_test.rb
For this conversation: https://github.com/ruby/debug/pull/213#discussion_r682389095
Proposal: 
- `obj receives #foo (C#foo)` for `C#foo`
- `C receives .bar (#<Class:C>.bar)` for `C.bar`
- `obj receives .singleton_foo` for singleton method
because we use `inspect`'s result, `obj` doesn't always look like an object. for example:
```
`#<ActiveRecord::Relation [#<Post id: 1, title: ...`
```
in such condition, that format isn't easy to read
```
`#<ActiveRecord::Relation [#<Post id: 1, title: ...`#where (ActiveRecord::Relation#where)`
```
so I think this is better
```
`#<ActiveRecord::Relation [#<Post id: 1, title: ...` receives #where (ActiveRecord::Relation#where)`
```
=> Simplify tracer's receiver message

test/support/utils.rb, test/test_utils_test.rb
Current test framework will raise TimeoutError if the test isn't finished correctly as follows. However, it's hard for users to make sense the meaning of errors. That's why I added `assert_finish` method to output clear failure messages.
```shell
Failure: test_outline_lists_local_variables(DEBUGGER__::OutlineTest):
#<Test::Unit::AssertionFailedError: TIMEOUT ERROR (10 sec) on LOCAL mode
[DEBUGGER SESSION LOG]
> DEBUGGER: Session start (pid: 11262)
> [1, 10] in /var/folders/kv/w1k6nh1x5fl7vx47b2pd005w0000gn/T/debugger20210821-11224-gdmbfn.rb
> =>   1| class Foo
>      2|   def initialize
>      3|     @var = "foobar"
>      4|   end
>      5|
>      6|   def bar; end
>      7|   def self.baz; end
>      8| end
>      9|
>     10| foo = Foo.new
> =>#0	<main> at …
```
=> Add assert_finish method to output clear failure messages when the test is not finished correctly

lib/debug/color.rb, lib/debug/thread_client.rb, lib/debug/tracer.rb, test/debug/trace_test.rb
Tracer's coloring follows the same rule as frame info's:
- `Cyan` for argument names.
- `Green` for paths.
- `Blue` for call identifier information.
- `Magenta` for return values.
(The colors may be affected by my machine's settings and could be different from yours.)
=> Colorize tracer's output

test/support/utils.rb
I want to use this message I had today as an example:
```
❯ ruby test/debug/trace_test.rb -n /test_trace_raise_prints_raised_exception/
Loaded suite test/debug/trace_test
Started
F
=========================================================================================================================================================================================================================
Failure: test_trace_raise_prints_raised_exception(DEBUGGER__::TraceRaiseTest):
Expected to include `/trace\/raise.+RuntimeError: foor/` in
(
DEBUGGER (trace/raise) #th:1 #depth:1  #<RuntimeError: foo> at /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debugger20210821-25153-1o8iqjb.rb:2
[1, 6] in /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debugger20210821-25153-1o8iqjb.rb
1| begin
2| …
```
=> Improve test failure's messages

test/debug/trace_test.rb
Although the tempfile is shared between 3 modes (`local`, `tcp remote` and `unix domain socket`), the tracer uses `w` mode to open the file. So eventually the file will only have output from one mode.
```
❯ ruby -Ilib test/debug/trace_test.rb -n /test_trace_with_into/
Tests on local and remote. You can disable remote tests with RUBY_DEBUG_TEST_NO_REMOTE=1.
Loaded suite test/debug/trace_test
Started
"PID:97079 CallTracer (disabled) into: /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/tracer_into20210901-97064-s9y8k0.rb\n" +
"DEBUGGER (trace/call) #th:1 #depth:2 >  Object#foo at /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debugger20210901-97064-ddvws9.rb:1\n" +
"DEBUGGER (trace/call) #th:1 #depth:2 <  Object#foo #=> 11 at /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debugger202109 …
```
=> Trace into test should only be ran in local mode

lib/debug/thread_client.rb, lib/debug/tracer.rb, test/debug/config_test.rb
If the `skip_path` option is configured, stepping through the matched frames would not be possible anyway. So the recorder should not record those frames to speed up recording.
In my Rails application, the recorder is basically unusable when it records every line execution, which could be hundreds of thousands of them (I don't know because it never finished recording). But after I applied the `skip_path` pattern I have (`/lib/`), I only need to wait a few extra seconds (with 685 records).
=> Apply skip_path to recorder

lib/debug/tracer.rb, test/debug/trace_test.rb
It also changes the pattern displayed in the message to make it easier to understand:
**Before**
```
Enable ExceptionTracer (enabled) with pattern (?-mix:foo)
```
**After**
```
Enable ExceptionTracer (enabled) with pattern /foo/
```
=> Filter ExceptionTracer with exception info

lib/debug/session.rb, test/debug/bp_test.rb
Fixes #248 
```
Started GET "/posts" for 127.0.0.1 at 2021-09-04 14:28:10 +0800
(0.6ms)  SELECT sqlite_version(*)
(0.1ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
Processing by PostsController#index as HTML
[2, 11] in ~/projects/sentry-ruby/sentry-rails/examples/rails-6.0/app/controllers/posts_controller.rb
2|   before_action :set_post, only: [:show, :edit, :update, :destroy]
3|
4|   # GET /posts
5|   # GET /posts.json
6|   def index
=>   7|     binding.b(do: "pp 123")
8|     @posts = Post.all
9|     # binding.b(do: "trace off")
10|   end
11|
=>#0    PostsController#index at ~/projects/sentry-ruby/sentry-rails/examples/rails-6.0/app/controllers/posts_controller.rb:7
#1 …
```
=> Auto-continue should use the same procedure as normal continue

test/debug/kill_test.rb, test/debug/quit_test.rb, test/support/assertions.rb, test/support/utils.rb
Currently, `assert_finish` method is automatically executed in the test framework. However, @ko1 pointed out that it would be more helpful to write it on test files directly. This PR fix it.
=> Modify `assert_finish` method so that it can be written directly to test files.

lib/debug/session.rb
It's only used by the DAP server so our tests don't cover it.
Fixes #252
=> Add Session#add_catch_breakpoint for non-repl (DAP) bp insertion

lib/debug/thread_client.rb
I crashed the debugger when I evaluated an expression that raises
`ActiveRecord::StatementInvalid` (probably unrelated to this issue):
```
["DEBUGGER Exception: /Users/st0012/projects/debug/lib/debug/thread_client.rb:961",
#<NoMethodError: undefined method `each' for nil:NilClass>,
["/Users/st0012/projects/debug/lib/debug/thread_client.rb:364:in `rescue in frame_eval'",
"/Users/st0012/projects/debug/lib/debug/thread_client.rb:345:in `frame_eval'",
"/Users/st0012/projects/debug/lib/debug/thread_client.rb:780:in `wait_next_action_'",
"/Users/st0012/projects/debug/lib/debug/thread_client.rb:660:in `wait_next_action'",
```
And based on Ruby's official document, [`Exception#backtrace_locations` can be `nil`](https://ruby-doc.org/core-3.0.1/Exception.html#method-i-backtrace_locations).
So we …
=> Some exceptions' backtrace_locations can be nil

lib/debug/config.rb
Some environments (ie. base Ubuntu image for Docker) intentionally
leave the locale setting blank, causing it to default to US-ASCII,
which may trigger an exception for invalid byte sequences.
Closes #258
=> Force encoding to UTF-8 when reading `session.rb`

README.md
When I read the documentation, I thought it was saying I could use debug with `binding.irb` and `binding.pry` because of the wording that was chosen. I hope this change helps others to understand that the reference to those methods are simply examples to help readers understand how to use `binding.break`.
=> Expand explanation of usage in source code

lib/debug/server_dap.rb
Handles the `filters` argument passed to a `setExceptionBreakpoints` request.
Some editors use this mandatory argument instead of optional `filterOptions`.
ref: https://microsoft.github.io/debug-adapter-protocol/specification#Requests_SetExceptionBreakpoints
tested with dap-mode.el
=> DAP(setExceptionBreakpoints): Handle `filters` argument

lib/debug/tracer.rb
`ruby -w` prints the following warning
```
lib/debug/tracer.rb:221: warning: statement not reached
```
This PR fixes the problem.
=> Fix unreachable code

README.md, Rakefile, lib/debug/session.rb, test/debug/load_test.rb
prevent to load lib/debug.rb
old lib/debug.rb should not be allowed to load.
`require 'debug'` is needed to update the `$LOADED_FEATURE` cache
(maybe it is a workaround for the MRI's issue)
fix #275
=> No lib deubg

README.md, misc/README.md.erb
- Add command section anchor links to most usage entries.
- Add `information` and `tracing` entries to the usage section.
- Add anchor links to `binding.break` references.
=> Improve readme

test/debug/debug_statement_test.rb
Since we now have 3 statements to start a debug session, the tests should cover them all.
=> Improve tests for debug statements

ext/debug/debug.c
`DEBUGGER__` and `FrameInfo` are defined in Ruby, so they are not
automatically pinned.  `rb_mDebugger` and `rb_cFrameInfo` are static
global variables that hold references to these objects.  If compaction
happens, these static references can go bad.  To fix this, we register
the two references as "mark objects" so that the GC will automatically
pin the references.
Fixes: #272
=> Pin objects that are defined in Ruby.

lib/debug/session.rb
When running with a puma server with 2+ workers (processes), the debugger causes 2 errors when exiting the server:
I fixed them in separate commits. You can see the before/after comparison with debugging output in the commit messages.
=> Fix `ForkInterceptor`'s `at_exit` callback

lib/debug/tracer.rb, test/debug/trace_test.rb
**Before**
```
❯ ruby -Ilib -r debug target.rb
[1, 9] in target.rb
=>   1| binding.b(do: "trace object 1")
2|       def foo
3|         yield(1)
4|       end
5|
6|       foo do |int|
7|         puts(int)
8|       end
9|
=>#0    <main> at target.rb:1
(rdbg:binding.break) trace object 1
Enable ObjectTracer for 1 (enabled)
4: from target.rb:6:in `<main>'
3: from target.rb:3:in `foo'
2: from target.rb:6:in `block in <main>'
1: from /Users/st0012/projects/debug/lib/debug/tracer.rb:206:in `block in setup'
/Users/st0012/projects/debug/lib/debug/tracer.rb:100:in `minfo': undefined method `singleton_class?' for nil:NilClass (NoMethodError)
```
**After
```
❯ ruby -Ilib -r debug target.rb
[1, 9] in target.rb
=>   1| binding.b(do: "trace object 1")
2|       def foo …
```
=> Fix Tracer's handling on block calls

README.md, lib/debug/local.rb, lib/debug/server.rb, lib/debug/session.rb, test/debug/trap_test.rb
* use `SIGURG` to stop the debuggee execution for remote debugging.
* intercept `trap` methods for SIGINT on local debugging.
* introduce `sigint` command to execute application registerred SIGINT trap handler.
=> fix signal handling.

lib/debug/session.rb, test/debug/config_postmortem_test.rb
On the middle of Ruby program you can enter the postmortem session with exception.
```ruby
require 'debug'
DEBUGGER__::CONFIG[:postmortem] = true
begin
raise 'foo'
rescue => e
DEBUGGER__::SESSION.enter_postmortem_session e
end
binding.b
p 1
p 2
```
=> refactoring `enter_postmortem_session`

test/tool/test_builder.rb
Fix bin/gentest -h cli error.
By default when you enter bin/gentest -h, the error looks like:
test_builder.rb:196: syntax error, unexpected .., expecting ']' (SyntaxError)
...@content = lines.split("\n")[..-3].join("\n") + "\n#{content...
=> Fix gentest -h cli error in ruby2.6

lib/debug/console.rb
It seems that the gem is expecting Reline >= 0.2.7, but the current check in place would allow for 0.2.6
=> Fix Reline version check in console requiring 0.2.7

lib/debug/thread_client.rb
```
$ cat run.rdbg
p :hello
$ rdbg -x run.rdbg target.rb
(rdbg:run.rdbg) p :hello
eval error: undefined method `eval_binding' for nil:NilClass
```
=> use `TOPLEVEL_BINDING` if frame is not available

lib/debug/breakpoint.rb, test/debug/break_test.rb
```ruby
1.singleton_class #=> can't define singleton (TypeError)
```
For workaround, use `#class` method instead.
=> some object can't make singleton class.

debug.gemspec
debug 1.2.0 requires irb 1.3.6 or higher. Otherwise the following error occurs:
```
ruby test/fizz_buzz_test.rb
Run options: --seed 16198
#<ArgumentError: unknown keyword: :colorable>
["/Users/jnito/.rbenv/versions/3.0.1/lib/ruby/3.0.0/irb/color.rb:118:in `colorize_code'",
"/Users/jnito/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.2.0/lib/debug/color.rb:67:in `colorize_code'",
"/Users/jnito/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.2.0/lib/debug/source_repository.rb:74:in `get_colored'",
"/Users/jnito/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.2.0/lib/debug/session.rb:296:in `source'",
"/Users/jnito/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/debug-1.2.0/lib/debug/frame_info.rb:64:in `file_lines'", …
```
=> `colorable: true` option was introduced in irb 1.3.6

lib/debug/breakpoint.rb
Fixes two unused variable warnings:
```
debug/lib/debug/breakpoint.rb:440: warning: assigned but unused variable - e
debug/lib/debug/breakpoint.rb:461: warning: assigned but unused variable - e
```
=> Fix unused variable warnings

lib/debug/session.rb, lib/debug/thread_client.rb
I was catching up all the recent changes and I think some small changes can make the code easier to understand.
=> Refactor thread management methods

lib/debug/server_cdp.rb, lib/debug/session.rb, lib/debug/thread_client.rb
Current CDP server just returns evaluate results. However, it's hard for users to read them when multidimensional hashes or arrays. This PR fixes it.
=> Make multidimensional hashes and arrays easier to read in Chrome

test/tool/test_builder.rb
The current test generator adds just the scenario method when the generated file already exists. However, users want to add the `program` method if the source of the script file doesn't match the source of all `program` methods. This PR fixes it.
```ruby
def test_1635256878
debug_code(program) do
type 's'
assert_line_num 2
assert_line_text([
/\[1, 10\] in .*/,
/     1\| module Foo/,
/=>   2\|   class Bar/,
/     3\|     def self\.a/,
/     4\|       p 'hoge'/,
/     5\|       "hello"/,
/     6\|     end/,
/     7\|   end/,
/     8\|   Bar\.a/,
/     9\|   bar = Bar\.new/,
/    10\| end/,
/=>\#0\t<module:Foo> at .*/,
/  \#1\t<main> at .*/
])
type 'q!'
end
end
```
```ruby
class FooTest1635256743 < TestCase
def program
<<~RUBY
1| module Foo
2|   class Bar
3|     def self.a
4|       p 'hoge' …
```
=> Add the `program` method if the source of the script file doesn't match the source of all `program` methods in the file

lib/debug/server_cdp.rb
Fixes #361
The reason why the error occurs is that the breakpoint number is wrong. Current CDP server have breakpoint numbers in the origin array of breakpoints even though they change every time the item is removed from the array. This PR fixes it.
=> Make sure to get break numbers correctly in CDP server

lib/debug/server_cdp.rb
This PR supports two features.
1. "Activate breakpoints"(The rightmost icon in the image bellow)
2. "Force script execution"(The black arrow in the following picture)
=> Support several features in Chrome DevTools

README.md, lib/debug/session.rb
Corrects typo in the documentation: Kernal => Kernel
=> typos in documentation (Kernal => Kernel)

lib/debug/server_cdp.rb
Fixes #361
#361 is not fixed completely because values of `bps` are not updated correctly and recent change. This PR fixes two parts as follows:
1. Update values of `bps` when getting 'Debugger.removeBreakpoint'.
2. Set breakpoints correctly when getting 'Debugger.setBreakpointsActive'.
=> Fix bug that breakpoints still left even though they are removed in Chrome

lib/debug/server_cdp.rb
Currently, when we enter methods to output something to stdout such as `puts` or `p`, the output will be sent to the terminal as shown in the picture below. It would be useful to output them to Console instead of the terminal. This PR does it.
=> Output stdout to Console instead of the terminal

CONTRIBUTING.md, test/debug/break_test.rb, test/support/assertions.rb, test/support/utils.rb, test/test_utils_test.rb
Fixes #318
I also defined `assert_debuggee_out` method to fix #322
=> Fix bug that test framework gets stuck when debuggee outputs many lines

lib/debug/color.rb, test/debug/print_test.rb
Currently, if we evaluate an object with issue in its `#inspect` method, it'll crash the debugger:
```
(rdbg) foo
["DEBUGGER Exception: /Users/st0012/projects/debug/lib/debug/thread_client.rb:970",
#<RuntimeError: foo>,
["target.rb:4:in `inspect'",
"/Users/st0012/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pp.rb:304:in `pretty_print'",
"/Users/st0012/.rbenv/versions/3.0.2/lib/ruby/3.0.0/pp.rb:177:in `block in pp'",
"/Users/st0012/.rbenv/versions/3.0.2/lib/ruby/3.0.0/prettyprint.rb:253:in `block (2 levels) in group'",
"/Users/st0012/.rbenv/versions/3.0.2/lib/ruby/3.0.0/prettyprint.rb:280:in `nest'",
"/Users/st0012/.rbenv/versions/3.0.2/lib/ruby/3.0.0/prettyprint.rb:252:in `block in group'",
"/Users/st0012/.rbenv/versions/3.0.2/lib/ruby/3.0.0/prettyprint.rb:265:in `group_sub'", …
```
=> Make sure all inspection exception are gracefully handled

lib/debug/server_cdp.rb
Currently, $stdout may not return to its original value after evaluation when an error occurs. This PR fixes it.
=> Make sure that $stdout returns to its original value after evaluation in CDP

lib/debug/client.rb, test/client_test.rb
I don't think printing the stacktrace on unknown commands is very helpful to the user
=> do not print stacktrace on unknown util command

test/debug/control_flow_commands_test.rb
I was getting:
```
/Users/dorianmariefr/src/clones/debug/test/debug/control_flow_commands_test.rb:207: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
```
I'm on ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]
kind of surprising that this could be seen as multiple divisions but sure
=> fix warning about regexp division ambiguity

lib/debug/server_cdp.rb
=> Improve error messages when it evaluates expressions in Console

lib/debug.rb
This contains changes to support JRuby:
* Mask out continuation usage
* Mask out iseq usage
It also contains changes to align with CRuby 3.0.2, which claims to ship 0.1.0 (#298) but does not actually do so.
* "expand filenames in breakpoints" from https://github.com/ruby/ruby/commit/ed5d032ea33a465fd7152a236a4aca0ff5653bf3
* doc fixes from https://github.com/ruby/ruby/commit/1819652578e8f9fe3606f7a716ec4e427fc55f0a
Once this is merged it should be released as 0.2.1 and Ruby 3.x should update to use that version.
=> Support JRuby and update from CRuby 3.0

test/client_test.rb, test/support/test_case.rb
The following warnings are fixed in this PR.
```shell
warning: instance variable @temp_file not initialized
warning: ambiguous first argument; put parentheses or a space even after `/' operator
```
=> Fix several warnings when it runs tests

lib/debug/console.rb
The `File.exists?` method has been deprecated.
See https://docs.ruby-lang.org/en/2.7.0/File.html#method-c-exists-3F
FYI. I found the problem via RuboCop as below:
```console
$ bundle add rubocop
...
$ bundle exec rubocop --only Lint/DeprecatedClassMethods
...
lib/debug/console.rb:162:26: W: [Correctable] Lint/DeprecatedClassMethods: File.exists? is deprecated in favor of File.exist?.
if history && File.exists?(path = history_file)
^^^^^^^
62 files inspected, 1 offense detected, 1 offense auto-correctable
```
=> Change deprecated File.exists? to File.exist?

test/debug/outline_test.rb
It fails in https://github.com/ruby/ruby/pull/5045 because `Class` has an extra method which changes the formatting a bit.
cc @ko1
=> Improve OutlineTest matcher

lib/debug/server_cdp.rb
Currently, when a tab in Chrome DevTools is closed, the error occurs such as:
```terminal
DEBUGGER: Debugger can attach via TCP/IP (127.0.0.1:12345)
DEBUGGER: With Chrome browser, type the following URL in the address-bar:
devtools://devtools/bundled/inspector.html?ws=127.0.0.1:12345
DEBUGGER: ReaderThreadError: Unsupported: 8
["/Users/s15236/workspace/debug/lib/debug/server_cdp.rb:61:in `extract_data'",
"/Users/s15236/workspace/debug/lib/debug/server_cdp.rb:103:in `block in process'",
"/Users/s15236/workspace/debug/lib/debug/server_cdp.rb:102:in `loop'",
"/Users/s15236/workspace/debug/lib/debug/server_cdp.rb:102:in `process'",
"/Users/s15236/workspace/debug/lib/debug/server.rb:69:in `block (3 levels) in activate'", …
```
=> Continue the debuggee after detaching to Chrome

README.md, lib/debug/breakpoint.rb, lib/debug/session.rb, lib/debug/thread_client.rb, test/debug/watch_test.rb
`watch` is the only breakpoint command that doesn't support condition and command options (`if`, `do`, and `pre`). It's not by design and the inconsistency between it and other commands may confuse the users. So after discussing with @ko1, we're supporting those options on `watch` too.
=> Add condition and command support to watch command

CONTRIBUTING.md, test/debug/break_test.rb, test/debug/config_postmortem_test.rb, test/debug/control_flow_commands_test.rb, test/debug/info_test.rb, test/debug/kill_test.rb, test/debug/quit_test.rb, test/debug/session_test.rb, test/support/assertions.rb, test/support/utils.rb, test/test_utils_test.rb
Current test framework doesn't check if the debugger and debuggee program has exited. This PR fixes it. Also, I built-in "assert_finish" method to call it automatically instead of calling it as API.
=> Verify that the debugger and debuggee program have exited

lib/debug/server_cdp.rb
@ko1-san giving me the following bug report:
After setting breakpoints at a script snippet in Snippets pane, execute debugger. Then debugger raise an error such as:
```shell
DEBUGGER: ReaderThreadError: undefined method `[]' for nil:NilClass
["/Users/naotto/workspace/debug/lib/debug/server_cdp.rb:198:in `block in process'",
"/Users/naotto/workspace/debug/lib/debug/server_cdp.rb:106:in `loop'",
"/Users/naotto/workspace/debug/lib/debug/server_cdp.rb:106:in `process'",
"/Users/naotto/workspace/debug/lib/debug/server.rb:69:in `block (3 levels) in activate'",
"/Users/naotto/workspace/debug/lib/debug/server.rb:212:in `setup_interrupt'",
"/Users/naotto/workspace/debug/lib/debug/server.rb:67:in `block (2 levels) in activate'", …
```
=> Fix bug that debugger raise an error when breakpoints are set in script snippets 

lib/debug/server_cdp.rb
=> Show variables in the target frame in Chrome

README.md, misc/README.md.erb
As suggested in https://github.com/ruby/debug/issues/378#issuecomment-964858848
=> Update readme for the 'debugger' statement

lib/debug/thread_client.rb, test/debug/debugger_local_test.rb
I want to introduce a new concept called `Debugger locals`. The 2 I introduced in this PR are:
- `_raised_` - stores the last raised exception (after a catch breakpoint being triggered)
- `_returned_` - stores the last returned value (after a normal breakpoint being triggered on method return)
They're designed to help pass values between breakpoint and commands. For example:
- `catch Exception do: trace object _raised_` - pass caught exception to object tracer (super handy)
- `b FILE:line do:  p _returned_` - evaluate a method's return value without stopping the program 
They only exist in debugger's REPL and commands. And they **won't** affect user program's binding and are not accessible from user program.
Because it could be hard to correctly anticipate when those values are stored …
=> Implement Debugger Locals (`_raised_` and `_returned_`)

lib/debug/frame_info.rb, lib/debug/server_dap.rb, lib/debug/thread_client.rb, test/debug/debugger_local_test.rb, test/debug/info_test.rb
* `_returned_` -> `_return`
* `_raised_` -> `_raised`
* On `info` command, show `_...` instead of `%...`
* But if there is a local variable conflicts with special
variables, use `%...` and do not introduce special lvars.
=> change the special local variables

lib/debug/server_cdp.rb, lib/debug/session.rb, lib/debug/thread_client.rb
In this PR, I updated evaluation(related to #395) and properties parts to support for the current change.
Because current CDP is not consistent with DAP, there are some problems as follows:
- DAP has some features, such as the ability to see detailed information about each property and to display special local variables, but CDP does not.
- It's hard to maintain them.
=> Update several parts in CDP to support for the current change

lib/debug/server_cdp.rb
@ko1-san pointed out that error occurs after detaching to Chrome.
```ruby
module Foo
class Bar
def self.a
"hello"
end
end
loop do
Bar.a
end
bar = Bar.new
end
```
Set the breakpoint at line 7, then close the tab.
```shell
#<Thread:0x00007fed9cae4ac0@DEBUGGER__::SESSION@server@/Users/naotto/workspace/debug/lib/debug/session.rb:146 run> terminated with exception (report_on_exception is true):
/Users/naotto/workspace/debug/lib/debug/server_cdp.rb:305:in `readline': undefined method `pop' for nil:NilClass (NoMethodError)
from /Users/naotto/workspace/debug/lib/debug/session.rb:371:in `wait_command'
from /Users/naotto/workspace/debug/lib/debug/session.rb:331:in `block in wait_command_loop'
from /Users/naotto/workspace/debug/lib/debug/session.rb:330:in `loop'
from …
```
=> Fix bug that error occurs after detaching to Chrome

lib/debug/client.rb, lib/debug/prelude.rb
`--util=init` is secret feature to help auto-loading debug.gem
without any additional wirting (like `gem debug` in Gemfile).
This fix is:
* renaming the command line option from `--util=init` to `--util=setup-autoload`
to make clear the task.
* remove `--util=init -`.
* support zsh and fish.
=> rename `--util=init` to `--util=setup-autoload`

CONTRIBUTING.md, bin/gentest, lib/debug/server_dap.rb, test/dap/boot_config_test.rb, test/dap/break_test.rb, test/dap/detach_test.rb, test/dap/finish_test.rb, test/dap/hover_test.rb, test/dap/next_test.rb, test/dap/step_back_test.rb, test/dap/step_test.rb, test/support/utils.rb, test/tool/test_builder.rb
This PR adds the following features.
```shell
% ruby test/dap/step_test.rb
Tests on local and remote. You can disable remote tests with RUBY_DEBUG_TEST_NO_REMOTE=1.
Loaded suite test/dap/step_test
Started
F
================================================================================================================================================================================================================================================================================
Failure: test_step_works_correctly(DEBUGGER__::StepTest1638676609)
/Users/s15236/workspace/debug/test/support/assertions.rb:79:in `assert_block'
/Users/s15236/workspace/debug/test/support/utils.rb:634:in `block (2 levels) in run_dap_scenario'
/Users/s15236/workspace/debug/test/support/utils.rb:628:in `each' …
```
=> Add the test framework for DAP

lib/debug/server_cdp.rb, lib/debug/session.rb, lib/debug/thread_client.rb
=> Show exception messages in Chrome when debugger paused on an exception

README.md, lib/debug/config.rb, lib/debug/server.rb, lib/debug/server_cdp.rb
To use Chrome debugging, we need the following steps.
1. Execute Remote debugger such as `rdbg --open=chrome target.rb`
2. Open Chrome browser
3. Copy and paste the URL which is outputted from the terminal in Google Chrome
4. Open the `Source` pane.
The steps are long, so I implemented the setup method for Chrome to open the Chrome browser automatically. We can use Chrome debugging as follows:
1. Execute Remote debugger such as `rdbg --open=chrome target.rb
2. Open the `Source` pane.
The following video shows an example of this PR.
https://user-images.githubusercontent.com/59436572/138588196-00bb7d36-dfea-4fb5-9362-7708a91ebb63.mov
Note that I'll refactor the process for WebSocket.
=> Open Chrome automatically

lib/debug/breakpoint.rb, test/debug/break_test.rb, test/debug/catch_test.rb, test/debug/watch_test.rb
As of now, some types of breakpoints don't respect the `skip_path` config:
- `MethodBreakpoint`
- `CheckBreakpoint`
- `WatchIvarBreakpoint`
This PR fixes the issue.
=> Breakpoints should respect the `skip_path` config

lib/debug/frame_info.rb
=> Use RbConfig::CONFIG instead of DEBUGGER__::CONFIG for pretty path

lib/debug/server_cdp.rb
There's no `@web_sock` anymore. So when sending error response it'll cause:
```
❯ exe/rdbg --open=chrome target.rb
DEBUGGER: Debugger can attach via TCP/IP (127.0.0.1:49402)
#<Thread:0x00007f8bfd23a4c0@DEBUGGER__::SESSION@server /Users/st0012/projects/debug/lib/debug/session.rb:148 run> terminated with exception (report_on_exception is true):
6: from /Users/st0012/projects/debug/lib/debug/session.rb:168:in `block in activate'
5: from /Users/st0012/projects/debug/lib/debug/session.rb:198:in `session_server_main'
4: from /Users/st0012/projects/debug/lib/debug/session.rb:295:in `process_event'
3: from /Users/st0012/projects/debug/lib/debug/server_cdp.rb:590:in `cdp_event'
2: from …
```
=> Update ivar name in send_fail_response

lib/debug/server_cdp.rb
Currently, debugger doesn't stop at the final line in Chrome when it proceeds with `StepOver'.
```ruby
a = 1
b = 2
c = 3
d = 4
e = 5 # <- doesn't stop here
```
The reason is that order of appending debug commands is incorrect. This PR fixes it.
=> Fix bug that debugger doesn't stop at the final line in Chrome

lib/debug/server_dap.rb
using `IRB::InputCompletor::retrieve_completion_data`.
This method doesn't return type information so maybe we need to
rewrite it.
=> support completion on DAP

lib/debug/server_cdp.rb
When Google Chrome is not installed, the debugger would fail to start it and then the TCP connection would fail too.
But with some Chromium-based browsers installed (e.g. [Sidekick](https://www.meetsidekick.com/)), the user can still use them as CDP frontends. So we shouldn't let the exception stop debugger.
**Before**
```
DEBUGGER: Debugger can attach via TCP/IP (127.0.0.1:52138)
#<Errno::EADDRNOTAVAIL: Can't assign requested address - connect(2) for 127.0.0.1>
Can't assign requested address - connect(2) for 127.0.0.1
["/Users/st0012/.rbenv/versions/2.7.4/lib/ruby/2.7.0/socket.rb:64:in `connect'",
"/Users/st0012/.rbenv/versions/2.7.4/lib/ruby/2.7.0/socket.rb:64:in `connect_internal'",
"/Users/st0012/.rbenv/versions/2.7.4/lib/ruby/2.7.0/socket.rb:1 …
```
=> Rescue EADDRNOTAVAIL when Chrome is not automatically started

lib/debug/server.rb, lib/debug/server_dap.rb
=> skip cleanup code

lib/debug/server_cdp.rb
Debugger sometimes doesn't open Chrome automatically because the debugger doesn't wait for the response of 'Page.navigate' method. This PR fixes it.
=> Fix bug that debugger sometimes doesn't open Chrome automatically

lib/debug/server_cdp.rb
#445 was an ad hoc solution and this PR fixes it correctly.
The reason of the bug is that the debugger doesn't call 'Page.enable'.
=> Correct changes in #445

lib/debug/server_cdp.rb
=> Show objects when a hovered expression is a specific class in Chrome

lib/debug/server_dap.rb
Fixes #460.
The reason of this bug is that debugger matches characters after the dot when expressions are constant variables. That's why this PR ensure that debugger doesn't match any characters after the dot.
=> Do not match any characters after the dot in an expression

lib/debug/server_cdp.rb
When "respond_fail" method is called, debugger raise an Exception as follows:
```shell
#<Thread:0x00007fc98c067568@DEBUGGER__::SESSION@server /Users/naotto/workspace/debug/lib/debug/session.rb:147 run> terminated with exception (report_on_exception is true):
/Users/naotto/workspace/debug/lib/debug/server_cdp.rb:527:in `respond_fail': wrong number of arguments (given 2, expected 1) (ArgumentError)
from /Users/naotto/workspace/debug/lib/debug/server_cdp.rb:551:in `fail_response'
from /Users/naotto/workspace/debug/lib/debug/server_cdp.rb:632:in `cdp_event'
from /Users/naotto/workspace/debug/lib/debug/session.rb:294:in `process_event'
from /Users/naotto/workspace/debug/lib/debug/session.rb:197:in `session_server_main'
from /Users/naotto/workspace/debug/lib/debug/session.rb:167:in `block in …
```
=> Give correct arguments to "respond_fail" method

lib/debug/server_cdp.rb
=> Use "DEBUGGER__.safe_inspect" when objects are inspected

lib/debug/server_cdp.rb
Because Chrome sometimes fails to get the frame id when it navigates current page to the given URL, we add frameId as a param.
Fixes #474.
=> Send current page's frame id when debugger sends 'Page.navigate' method

test/support/dap_utils.rb
`omit` provides cleaner messages. 
**pend**
```
=====================================================================================================================================================================================================================================================================================================================================================
Pending: test_break_works_correctly(DEBUGGER__::BreakTest1638674577): Tests for DAP were skipped. You can enable them with RUBY_DEBUG_DAP_TEST=1.
/Users/st0012/projects/debug/test/support/dap_utils.rb:168:in `run_dap_scenario'
test/dap/break_test.rb:21:in `test_break_works_correctly'
18:     RUBY
19:
20:     def test_break_works_correctly
=> 21:       run_dap_scenario PROGRAM do
22:         [
23: …
```
=> Use omit to skip tests

test/debug/debug_statement_test.rb
Just found that this usage is not covered by tests yet.
=> Add test case for DEBUGGER__.step_in

lib/debug/console.rb
Fixes #497 
The issue is caused by special characters be converted into the autocompletion's RegExp directly, like `/\Aargs[/`.
It can be reproduced by typing `args[` and `tab` to trigger the completion callback:
```
❯ exe/rdbg target.rb
[1, 1] in target.rb
=>   1| a = 1
=>#0    <main> at target.rb:1
(rdbg) args[#<Thread:0x00007fa74da10c60@DEBUGGER__::SESSION@server /Users/st0012/projects/debug/lib/debug/session.rb:147 run> terminated with exception (report_on_exception is true):
29: from /Users/st0012/projects/debug/lib/debug/session.rb:167:in `block in activate'
28: from /Users/st0012/projects/debug/lib/debug/session.rb:197:in `session_server_main'
27: from /Users/st0012/projects/debug/lib/debug/session.rb:253:in `process_event'
26: from …
```
=> Escape autocompletion word before putting it into Regexp

lib/debug/thread_client.rb, test/debug/frame_control_test.rb
The cause of #502 is frame operations don't set the `ThreadClient`'s location. So the `break` command gets the incorrect location when adding new breakpoints after the current frame is changed.
I think the best solution to this problem is to avoid manual location assignment altogether. Since there aren't any case that we want the TC's location be different from its current frame, delegating the location to its current frame's should be the simplest solution.
=> Avoid manually setting ThreadClient's location

lib/debug/thread_client.rb
Currently it's still hard to colorize and truncate the inspected value at the same time. But we can at least colorize the variable name so it looks like other normal-size locals.
This PR also fixes a small miscalculation when appending `>` to Ruby object's inspection value.
**Before**
**After**
=> Colorize oversized local's variable name

lib/debug/server.rb, lib/debug/server_cdp.rb
* Disable ScreenCast displays
* Open Source panel automatically.
=> Add query parameters to URL to use the debugger easily

test/support/dap_utils.rb
A thread for storing debuggee's output is defined https://github.com/ruby/debug/blob/master/test/support/utils.rb#L333 as a `reader_thread` in remote_info. However, it's overridden in https://github.com/ruby/debug/pull/511/files#diff-a1bc4fb86b4a4e8cc3d94199a4d2b9152c2c8da2261be54d0529942f64a8105dL155. This PR fixes it.
=> Do not override an existed thread in the testing framework

test/support/dap_utils.rb
kill_remote_debuggee method closes read and write stream.
https://github.com/ruby/debug/blob/089ae90a5c556d7b3a6f57ff9cbc07f9f35b33b3/test/support/utils.rb#L304
=> Use "kill_remote_debuggee" instead of "kill_safely" method

lib/debug/source_repository.rb
From Ruby 3.1, a path given by eval does not return by
`ISeq#absolute_path`.
fix #479
With this fix, use `File.readlines(chomp: true)`.
=> use `ISeq#path` with `ISeq#absolute_path`

test/support/dap_utils.rb, test/support/utils.rb
This PR spell-checks a method name used in tests.
=> test: Fix a typo in method name

README.md, lib/debug/breakpoint.rb, lib/debug/session.rb, test/debug/break_test.rb, test/support/test_case.rb
It should distinguish if path is a string or a regexp and match them with the path in different ways.
=> Fix breakpoints' path option

README.md, misc/README.md.erb
I got feedback from Rubyists saying that they thought the debugger only works with Ruby 3.1. Given that it's mostly advertised with the Ruby 3.1 release, I can understand why they make that assumption. So I think we can mention the supported Ruby version and platform in the readme to make it clearer.
=> Mention Ruby version requirement in Readme

lib/debug/local.rb
Process.waitpid by default waits for its child to exit. So there's no need to wrap a loop around it.
What happens in #485 is that the loop keeps running until it's killed by puma with a `KILL` signal.
**Before**
```
[27096] Puma starting in cluster mode...
[27096] * Puma version: 5.5.2 (ruby 3.0.2-p107) ("Zawgyi")
[27096] *  Min threads: 1
[27096] *  Max threads: 1
[27096] *  Environment: development
[27096] *   Master PID: 27096
[27096] *      Workers: 2
[27096] *     Restarts: (✔) hot (✔) phased
[27096] * Listening on http://127.0.0.1:3000
[27096] Use Ctrl-C to stop
DEBUGGER: Attaching after process 27096 fork to child process 27114
[27096] - Worker 0 (PID: 27114) booted in 0.01s, phase: 0
DEBUGGER[puma: cluster worker 0: 27096 [DebugPuma]#27116]: Attaching after process 27114 fork to …
```
=> Don't wrap loop around waitpid call

test/support/dap_utils.rb
Current test framework for DAP doesn't check if a debuggee finishes after all scenarios. This PR fixes it.
=> Make sure to fail DAP's tests when a debuggee does not finish after all scenarios

lib/debug/server.rb
Because this expression is already checked in the previous process.
=> Remove useless if statement

README.md, misc/README.md.erb
Since users don't Toggle Device Toolbar in #510, explanations are unnecessary.
=> Remove explanations about how to disable ScreenCast displays

lib/debug/breakpoint.rb, lib/debug/session.rb, lib/debug/thread_client.rb
On Ruby 3.1 there is `TracePoint.allow_reentry` method to allow
reentrant TracePoint events and it allows us to enable nested
breakpoints.
=> Allow reentrant breakpoint on Ruby 3.1

test/support/dap_utils.rb, test/support/protocol_utils.rb
Fixes https://github.com/ruby/debug/issues/567.
One of possible reason of this bug is that attaching to debuggee is too early. This PR fixes it
=> Wait for debugger to run completely in the test framework for DAP

lib/debug/session.rb, lib/debug/thread_client.rb
Just some things I found recently.
=> Small refactors

lib/debug/console.rb, lib/debug/thread_client.rb, test/debug/nested_break_test.rb
=> Restore frames on nested break

lib/debug/breakpoint.rb, lib/debug/session.rb, test/debug/break_test.rb
1. `break if: cond` doesn't support commands like `do:` or `pre:`. This PR adds the support.
2. To make missing option support noticeable in the future, I've centralized `Breakpoint`'s options processing to the parent class as keyword arguments. This requires the options (`path`, `command` and `cond` for now) to be explicitly provided. It should make missing support of them more noticeable.
=> Support command on CheckBreakpoint

lib/debug/server_dap.rb, lib/debug/thread_client.rb, test/protocol/step_back_raw_dap_test.rb
1. Use `get_frame` to retrieve frames with the given frame index.
2. Use `collect_locals` to retrieve the locals from the given frame.
- This also fixes an issue that `%self` isn't displayed in DAP when stepping backward. 
Thanks to the DAP tests written by @ono-max, I feel a lot comfortable doing such refactoring now 👍
=> Unify frame and locals collection implementation between ThreadClient and servers

lib/debug/breakpoint.rb, lib/debug/session.rb
On Windows and some other file systems, they support case insensitve
filenames.  This patch almost supports case insensitve file name
on break command. Maybe we need more features to support case insensitve
file names, so reports are welcome.
fix https://github.com/ruby/debug/issues/554
=> Support case insensitive filename

lib/debug/server_dap.rb, lib/debug/session.rb
`setBreakpoints` requests specify a set of "enabled lines" in
a specified path. In otherwords, if existing breakpoins in specified
path are not in a set, they should be removed.
fix https://github.com/ruby/debug/issues/519
fix https://github.com/ruby/vscode-rdbg/issues/17
=> clear removed breakpoints.

lib/debug/session.rb
`UI_*Server` access to SESSION object in the server thread, but
it can be not initialized yet at this point.
This patch makes sure the SESSION is initialized when the
`UI_*Server` is created.
=> make sure `SESSION` is initialized

lib/debug/server_dap.rb
On Windows (or some other platform), `SIGURG` is not supported
so use `TRAP_SIGNAL` instead.
fix https://github.com/ruby/debug/issues/506
=> use `TRAP_SIGNAL` instead of :SIGURG

lib/debug/server_dap.rb
I hope I don't misunderstand the intention, but since both `instance_variable_get` and `local_variable_get` raises `NameError` when the variable is not defined, manually raising them seem redundant.
=> Remove unnecessary variable checks

lib/debug/server_cdp.rb, lib/debug/server_dap.rb
First commit is similar to https://github.com/ruby/debug/pull/581
Second commit is to align `evaluate` with the current evaluation logic in `ThreadClient`.
=> Refactor servers

lib/debug/session.rb
DAP sends a path like `c:\\ko1\\t.rb` but we uses `c:/ko1/t.rb`
style path (in MRI) so we need to translate between them.
fix https://github.com/ruby/debug/issues/588
=> Expand path for `clear_line_breakpoints`

lib/debug/session.rb, test/protocol/hover_raw_dap_test.rb
Ruby 3.1 calls `_fork` from `Kernel#fork` and `Process.fork` (and so on)
so we only need to wrap `_fork`. This patch is required to wrap `fork`
features as a nearest wrapper for `_fork`.
fix https://github.com/ruby/debug/issues/273
=> wrap `_fork` from Ruby 3.1

lib/debug/client.rb, lib/debug/server.rb
* `--util=gen-portpath` shows default portpath file path.
* `--port 0:PATH` saves a assigned port to PATH.
They are used by VSCode IDE integration.
=> `gen-portpath` utility

lib/debug/server_dap.rb
fix https://github.com/ruby/debug/issues/523
=> send `terminated` event when exit

lib/debug/server.rb, lib/debug/server_dap.rb, lib/debug/session.rb
Windows doesn't support UNIX domain socket so it should use
TCP/IP instead. This patch allows Windows to use TCP/IP.
=> Support `open_frontend` on Windows

test/support/protocol_utils.rb, test/support/utils.rb
There are 2 fixes in this PR:
1. `@sock` or `@web_sock` may not always present. For example, I was getting:
```
Error: test_break_stops_at_correct_place(DEBUGGER__::BreakTest1):
NoMethodError: undefined method `cleanup' for nil:NilClass
@web_sock.cleanup
^^^^^^^^
/Users/st0012/projects/debug/test/support/protocol_utils.rb:275:in `ensure in execute_cdp_scenario'
/Users/st0012/projects/debug/test/support/protocol_utils.rb:278:in `execute_cdp_scenario'
/Users/st0012/projects/debug/test/support/protocol_utils.rb:47:in `run_protocol_scenario'
test/protocol/break_test.rb:20:in `test_break_stops_at_correct_place'
17:     RUBY
18:
19:     def test_break_stops_at_correct_place
=> 20:       run_protocol_scenario PROGRAM do
21:         req_add_breakpoint 5
22:         req_continue
23: …
```
=> Improve protocol tests error handling

lib/debug/server_dap.rb
When debugging on the other machine (non-local fs) with TCP/IP,
the source should be sent each time.
This patch check the local filesystem or not and if it is not a
local filesystem, specify `sourceReference` (and VSCode send
`source` request to get a whole source code).
On the TCP/IP, debugger assumes it is non-local fs, but
`'localfs':true` in `launch.json` tells that VSCode and
debugger run on same machine (share the same local fs).
=> DAP: source on not local fs

lib/debug/server.rb, lib/debug/server_cdp.rb, lib/debug/server_dap.rb
We can assume listening loopback address should be localfs.
fix https://github.com/ruby/debug/issues/598#issuecomment-1083703639
=> Assume loopback server address is localfs

ext/debug/extconf.rb
On MRI, `rb_iseq_parameters` and `rb_iseq_code_location` are
supported on at least ruby 2.6 and later, and `rb_iseq_type`
is supported on 3.1.0 and later. This commit skips `have_func`
check (checked by `RUBY_VERSION`).
=> skip feature check on MRI

test/support/cdp_utils.rb, test/support/dap_utils.rb, test/support/protocol_utils.rb
```shell
$ rake test
Tests on local and remote. You can disable remote tests with RUBY_DEBUG_TEST_NO_REMOTE=1.
Tests for DAP were skipped. You can enable them with RUBY_DEBUG_PROTOCOL_TEST=1.
Loaded suite /Users/s15236/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/rake-13.0.6/lib/rake/rake_test_loader
Started
...................................................................O
=====================================================================================================================================================================================================================================================
Omission: Tests for CDP and DAP were skipped. You can enable them with RUBY_DEBUG_PROTOCOL_TEST=1. [test_break_stops_at_correct_place(DEBUGGER__::BreakTest1)] …
```
=> Print information that protocol tests are skipped only once

test/support/protocol_utils.rb
Since all protocol responses should be verified except for a few exceptions (e.g. DAP's `stepBack`), the verification should be performed automatically. This can prevent situations like https://github.com/ruby/debug/pull/559#discussion_r835736078 and also make the API easier to use (getting response from the same method call).
There are 2 exceptions though. Both of them are DAP requests:
- `stepBack` doesn't return response "yet".
- `stackTrace`'s response doesn't match the schema. I think this is something to be fixed in another PR.
This refactor can actually centralize those exceptions and make them easier to manage. And sooner or later they should go anyway.
=> Verify CAP/DAP requests automatically

lib/debug/breakpoint.rb, lib/debug/thread_client.rb, test/debug/break_test.rb
As described in #406
When a condition is fulfilled (e.g. `a >= 1`), it usually remains true for at least a while. However, under the current implementation, it'll stops at every single line after the condition becomes true, which is annoying.
So this PR introduces an extra state to make sure the BP doesn't stop repeatedly after the condition is fulfilled.
Closes #406
=> CheckBreakpoint should only stop at the first condition fulfillment line

Rakefile
Even after working on this project for almost a year, I still often forget to update the `README.md.erb` template instead of `README.md` if I haven't touch `README.md` for a while (I did that again in #618). So I think having a task to remind us about this would be nice.
=> Add a task to check if README is updated correctly

lib/debug/server_dap.rb, test/protocol/boot_config_raw_dap_test.rb, test/protocol/break_raw_dap_test.rb, test/protocol/call_stack_raw_dap_test.rb, test/protocol/catch_raw_dap_test.rb, test/protocol/detach_raw_dap_test.rb, test/protocol/eval_raw_dap_test.rb, test/protocol/finish_raw_dap_test.rb, test/protocol/hover_raw_dap_test.rb, test/protocol/next_raw_dap_test.rb, test/protocol/restart_raw_dap_test.rb, test/protocol/step_back_raw_dap_test.rb, test/protocol/step_raw_dap_test.rb, test/protocol/watch_raw_dap_test.rb, test/support/protocol_utils.rb
Currently, we always/usually set `sourceReference` to `null`, which is against the specification (it requires integer).
And according to the [specification](https://microsoft.github.io/debug-adapter-protocol/specification#Types_Source):
```
/**
* If sourceReference > 0 the contents of the source must be retrieved through
* the SourceRequest (even if a path is specified).
* A sourceReference is only valid for a session, so it must not be used to
* persist a source.
* The value should be less than or equal to 2147483647 (2^31-1).
*/
sourceReference?: number;
```
`0` means it won't trigger another `source` request, which we don't support yet. I can't find more information online about it (not many people discussing DAP, surprise!).
BTW, we should review the `sourceReference` implementation …
=> sourceReference should use 0 as default

lib/debug/session.rb, test/debug/config_fork_test.rb
If debugger is not active, it should call original `fork` but
it uses `yield` by mistake.
fix #623
=> call `super' (zsuper) to call original `fork`

CONTRIBUTING.md, test/protocol/threads_test.rb, test/support/protocol_utils.rb
Some notes:
- Ids don't always start from `0` and increment by `1`, as shown in the below example. So asserting ids is pointless imo.
- Threads request is only supported in DAP server.
- Example failure message:
```
result:
{
"type": "response",
"command": "threads",
"request_seq": 8,
"success": true,
"message": "Success",
"body": {
"threads": [
{
"id": 1,
"name": "#1 /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debug-20220411-21868-x0t9a2.rb:6:in `<main>'"
},
{
"id": 4,
"name": "#4 /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debug-20220411-21868-x0t9a2.rb:2:in `block in foo'"
}
]
},
"seq": 9
}.
Expect all thread names to be matched. Unmatched threads:
<[]> expected but was
<["#1 /var/folders/yg/hnbymwxd5pn7v94_clc59y6r0000gn/T/debug-20220411-21868-x0t9a2.rb:6:in `<main>'"]> …
```
=> Add `assert_threads_result` helper and threads test

lib/debug/breakpoint.rb, lib/debug/thread_client.rb
=> export `ThreadClient@check_bp_fulfillment_map`

CONTRIBUTING.md, lib/debug/server_dap.rb, lib/debug/session.rb, test/protocol/catch_raw_dap_test.rb, test/protocol/catch_test.rb, test/protocol/detach_raw_dap_test.rb, test/support/protocol_utils.rb
**Main Changes**
1. `Session#add_bp` should return either `nil` (duplicated bp being rejected) or the `Breakpoint` object. Currently it returns `true` for duplicated breakpoints (from `bp.delete`), which makes `setExceptionBreakpoints` returns `verify: true` incorrectly. (see the 3rd commit)
2. The `setExceptionBreakpoints` command should clear all breakpoints before creating the assigned ones. Otherwise, it's not possible to deactivate exception breakpoints. After the changes, its behavior would follow `setBreakpoints` command and [align with debugpy's implementation](https://github.com/microsoft/debugpy/blob/328d4026b16815807e43a26f60988da3de8c05a4/src/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_process_net_command_json.py#L839).
3. It supports setting conditions with exception …
=> Enhance DAP's `setExceptionBreakpoints` command

test/support/protocol_utils.rb
Improve error messages in ValidationError
Use the hash map to get ruby classes from JSON type instead of the method
=> Refactor some logic in "CDP_Validator" class

lib/debug/server_dap.rb, test/protocol/boot_config_raw_dap_test.rb, test/protocol/detach_raw_dap_test.rb
I can understand the default is designed as a convenient way to stop users' programs when an error happens. But because exception breakpoints stop when the errors are raised and don't care about if they'd be rescued, they can stop at unnecessary places. For example, the user's Rails app already handles the exception with a `rescue_from` callback, but he/she will still be stopped regardless.
I actually got multiple complaints/questions about it recently at Shopify as we're pushing for debugger adoption:
> Quick question - I'm using the debug gem in spin but it breaks every time it comes across a raise. Is this expected behaviour? If so, how can I turn it off and only break on my breakpoints?
From another user:
> the only annoying moment was with checkboxes in left down corner in …
=> Don't activate RuntimeError breakpoint by default

lib/debug/session.rb
When I did #628, I accidentally changed the semantic of `Session#restart_all_threads`, which caused #646. This PR reverts that change.
Closes #646
=> Fix threads restart

lib/debug/frame_info.rb, lib/debug/thread_client.rb
The DAP server doesn't use args and in some instances retrieving these is very slow.  Extracted them into their own methods to prevent this form slowing down DAP requests as the data is not used.
- Relates to #635
=> Move block and method args to their own methods

.github/workflows/protocol.yml, .github/workflows/ruby.yml, test/support/cdp_utils.rb, test/support/protocol_utils.rb, test/support/test_case.rb, test/support/utils.rb
I made these changes when debugging Ruby head's hanging issue and they did make the build failures easier to catch.
1. Both debuggee connection and workflows should have timeout
2. Rename `WebSocketClient#cleanup` to `#close` because that's all it does
3. Only perform cleanup logic when the socket/threads are present, which may not be the case when the error happens during test setup.
=> Protocol test framework improvements

Rakefile, lib/debug/breakpoint.rb, test/console/debugger_local_test.rb, test/console/outline_test.rb, test/console/print_test.rb
=> Fix some typos

lib/debug/server.rb
`@sock.gets` can return `nil` if `@sock` is closed.
Return this method and cleanup the server connection.
fix #622
=> return when `line` is `nil`

lib/debug/config.rb, lib/debug/session.rb, lib/debug/thread_client.rb
When working on features that involves Session <-> ThreadClient interaction, like #422, I often put multiple puts/pp in different places to see what's happening in the debugger. And then I feel that they're mostly about:
- Events being sent from ThreadClient.
- Commands being sent to ThreadClient.
- ThreadClient's mode change.
- ThreadClient's suspend event.
So I figure maybe we can add the `debug` log level and instrument them in a more uniformed format. I think it'll help ourselves debug issues and also help anyone who's interested in learning the debugger internal. And in some cases, having this information can help us debugging user issues as well.
Let's zoom in to the logs printed after the `c` command was entered. 
```
DEBUGGER (INFO): leave_subsession
DEBUGGER (DEBUG): #<DBG:TC …
```
=> Add debug log level and instrument important internal events

lib/debug/config.rb, lib/debug/server_dap.rb, lib/debug/thread_client.rb
`CONFIG.skip_all` is called to ignore cleanup code.
fix #552
=> introduce `CONFIG.skip_all`

lib/debug/session.rb, lib/debug/thread_client.rb
`DEBUGGER__.debug` can be called many times so the building messages
should be lazy.
=> Create message lazily for `DEBUGGER__.debug`

lib/debug/frame_info.rb, lib/debug/server_dap.rb, lib/debug/session.rb, lib/debug/thread_client.rb, lib/debug/tracer.rb
=> support BasicObject

lib/debug/server_dap.rb
=> support `levels` and `startFrame` of`stackTrace`

lib/debug/server_dap.rb, lib/debug/session.rb
* Stop `pp` when the output exceeds the maximum length
* Use `PP.singleline_pp` to disable breaking features
fix #635
This does not solve the problem if the `pretty_print` consumes
time for example using network connections.
=> `PP` trick for long `inspect` code

README.md, lib/debug/config.rb, lib/debug/console.rb, lib/debug/server.rb, lib/debug/session.rb, lib/debug/thread_client.rb, misc/README.md.erb, test/console/config_test.rb
Currently, we use `CONFIG[:key] || default` to apply default values at the places we use the config. This has 2 problems:
1. The config descriptions' default and the actual default needs to be synced manually. And as the time goes by, some of them are likely to be out-of-sync gradually.
2. Config defaults are scattered around the codebase and you need to know where a config is used to see its default. With code searching this isn't a big issue but it's still nicer to see all of them in one place.
So in this PR, I moved all configs' default to the `config.rb`, just right after the config type info. And now the default is synced between `README <-> config command <-> actual logic`.
**Before**
```
(rdbg) config    # command
log_level = (default)          # UI: Log level same as Logger …
```
=> Centralize configuration defaults

.github/workflows/protocol.yml, .github/workflows/ruby.yml
fail-fast defaults to true, meaning that when a CI job fails, all the
other ones are cancelled. CI is flaky, so we shouldn't cancel other CI
jobs when one fails.
=> Don't fail fast on CI

lib/debug/config.rb, lib/debug/frame_info.rb, lib/debug/session.rb, lib/debug/thread_client.rb, test/console/backtrace_test.rb, test/console/config_test.rb, test/support/console_test_case.rb, test/support/test_case.rb
I want to add recommend configs like this to Rails projects:
```rb
DEBUGGER__::CONFIG[:skip_path] = Gem.path.join(":")
DEBUGGER__::CONFIG[:use_short_path] = true
```
Ideally, it'll reduce the full backtrace output from
```
=>#0    Post#title at ~/projects/rails-guide-example/app/models/post.rb:7
#1    block {|attribute=:title|} in validate at ~/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activemodel-7.0.1/lib/active_model/validator.rb:150
(rdbg) bt    # backtrace command
=>#0    Post#title at ~/projects/rails-guide-example/app/models/post.rb:7
#1    block {|attribute=:title|} in validate at ~/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activemodel-7.0.1/lib/active_model/validator.rb:150
#2    [C] Array#each at ~/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activemodel-7.0.1/lib/act …
```
=> Support per-project config file and fix backtrace filtering

lib/debug/config.rb, lib/debug/frame_info.rb, lib/debug/thread_client.rb, test/console/backtrace_test.rb, test/console/config_test.rb, test/support/console_test_case.rb, test/support/test_case.rb
1. When comparing paths, we need to expand the values for accurate result. This is because frame paths are usually presented unexpanded:
```
~/.rbenv/versions/3.1.0/lib/ruby/3.1.0/irb/workspace.rb
```
But important Ruby/Rubygem paths are all stored expanded:
```
RbConfig::CONFIG["rubylibdir"] #=> "/Users/st0012/.rbenv/versions/3.1.0/lib/ruby/3.1.0"
Gem.path #=> ["/Users/st0012/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0", "/Users/st0012/.gem/ruby/3.1.0"]
```
2. We shouldn't use `FrameInfo#location_str` for frame filtering because it's mainly for displaying and its value can be changed by the `use_short_path` config. As an alternative, I added `FrameInfo#real_location` for that purpose.
3. The `pty_home_dir` should be just the original `HOME` on CI because 
1. We don't need to alter home …
=> Fix frame skipping logic

exe/rdbg
**This is a leftover issue caused by https://github.com/ruby/debug/pull/642**
When a remote debugger client is started, it doesn't have configurations filled like the debuggee does, which can cause some issues. Like:
```
disconnected (undefined method `empty?' for nil:NilClass
if !history_file.empty?
^^^^^^^)
```
This is because `CONFIG.update` replaces the entire config hash and removes all the default values `CONFIG` already has. So if we start a client with `rdbg -A`, this will happen:
1. `config = DEBUGGER__::Config::parse_argv(ARGV)` returns a hash like `{ mode: :attach }`.
- The `mode` isn't a real configuration option. It's only used to pass the mode information from the `-A` flag.
2. The `CONFIG` will be initialized with all the default configuration values.
- `{:mode=>:start, …
=> Fix remote client configuration

lib/debug/server_dap.rb
=> Limited to inspect string in 4KB on DAP

exe/rdbg, lib/debug/session.rb
`rdbg` adds `-r debug/(start_method)` to tell the launched ruby
process needs require it. However, this option affect child process.
This patch restore the `RUBYOPT` if needed.
fix #663
=> restore modified `RUBYOPT` by `rdbg`

lib/debug/thread_client.rb
=> skip if `ThreadClient.current.management?`

lib/debug/thread_client.rb, test/console/record_test.rb
Debugger doesn't work after stopping record once as follows:
```shell
$ exe/rdbg g.rb
[1, 6] in g.rb
=>   1| a=1
2|
3| b=1
4|
5| c=1
6| p a
=>#0	<main> at g.rb:1
(rdbg) record on    # command
Recorder for #<Thread:0x000000013007bc60 run>: on (0 records)
(rdbg) record off    # command
Recorder for #<Thread:0x000000013007bc60 run>: off
(rdbg) record on    # command
Recorder for #<Thread:0x000000013007bc60 run>: off
(rdbg) b 5    # break command
#0  BP - Line  /Users/s15236/workspace/debug/g.rb:5 (line)
(rdbg) c    # continue command
[1, 6] in g.rb
1| a=1
2|
3| b=1
4|
=>   5| c=1
6| p a
=>#0	<main> at g.rb:5
Stop by #0  BP - Line  /Users/s15236/workspace/debug/g.rb:5 (line)
(rdbg) step back    # command
Can not step back more.
```
```shell
$ exe/rdbg g.rb
[1, 6] in g.rb
=>   1| a=1
2|
3| b=1 …
```
=> Fix bug that "record on" doesn't work after stopping record once

README.md, misc/README.md.erb
I think a table that quickly summarizes all the approaches to open the remote debuggee can help users decide the best approach to pick. 
I also think we can leave this table and maybe a piece of quick intro in the README, and move most of the remote debugging doc to a separate file (e.g. `docs/remote_debugging.md`). Reasons:
- Some users never need to use remote debugging, so they don't need to see those doc every time they are here to see other information.
- For those who does use remote debugging, they may need the docs probably the first 2~3 times they use/set up the project. And then they also won't need to see these docs often.
=> Add a summary table on starting remote debuggee

test/console/debugger_local_test.rb, test/console/record_test.rb, test/support/console_test_case.rb, test/support/protocol_test_case.rb
So the tests won't fail because of changes like https://github.com/ruby/ruby/pull/4857
=> Make tests `Exception#inspect` independent

lib/debug/session.rb, test/console/config_test.rb
`config append foo bar` doesn't work (it worked as `config set foo bar`).
=> fix `config append foo bar`

README.md, misc/README.md.erb
This closes #676 whose root cause was "user did not follow README instructions closely enough." ;-)
- reinforced the need for debug 1.x when debugging in a Bundler project
=> Add warning about legacy debug gem

lib/debug/config.rb, lib/debug/server_dap.rb
On DAP via TCP/IP connection, all the source code are detected
as remote files (without `localfs:true` in launch.json for VSCode).
In this case, DAP clients (VSCode, ...) receive the contents
of the file from DAP server and open an editor window in readonly mode.
`local_fs_map` configuration can set remote->local path translation.
For example,
```
RUBY_DEBUG_LOCAL_FS_MAP=/remote/src/:/local/src/ rdbg -O --port=...
```
On this case, if remote path is `/remote/src/is/foo.rb`, then DAP
returns `/local/src/is/foo.rb` and open the local file as writable
mode.
You can specify multiple path maps with ',' character like
```
RUBY_DEBUG_LOCAL_FS_MAP=/r1/:/l1/,/r2/:/l2/ ...
```
and also you can specify this map within launch.json for VSCode like:
```
{
"type": "rdbg",
"name": "Attach with rdbg …
```
=> local_fs_map for DAP

README.md, misc/README.md.erb
I think using a table can make this section even more easier to understand while providing more information.
**Before**
**After**
=> Update remote debugging overview with table

lib/debug/server.rb, lib/debug/server_dap.rb, test/protocol/detach_raw_dap_test.rb, test/protocol/detach_test.rb
=> nonstop at attach on DAP

lib/debug/server_dap.rb
This message can be received while in the subsession or not
(running debuggee program) and it should change the handling.
Also `UI_DAP#event` can be called after closing the socket
so so `send` should check `@sock` is available or not.
fix #630
=> check `in_subsession?` on disconnect request

lib/debug/server_dap.rb, lib/debug/session.rb
- ignore not avilable files
- Introduce `UI_DAP.local_to_remote_path`
=> DAP local to remote path

README.md, lib/debug/config.rb, lib/debug/console.rb
It doesn't show any hint on the REPL.
fix #538
=> `no_hint` configuration option

lib/debug/client.rb
Support `-e` option on the attach client with `rdbg -A`.
`rdbg -A -e 'p 1'` will execute `p 1` at first and user can input
debug commands on REPL.
=> support `-e` option for client

lib/debug/client.rb, lib/debug/server.rb, lib/debug/version.rb
* Attach with `-n` option doesn't stop the debuggee process.
* Introduce `parse_option` method for an extensible greeting message.
* Show the debuggee information at connecting.
=> support `rdbg -n --attach`

lib/debug/config.rb
irb seems supporting `NO_COLOR` so debug.gem also supports it.
ref: https://no-color.org/
ref: https://github.com/ruby/irb/pull/105
=> Respect `NO_COLOR` environment variable

lib/debug/server_dap.rb
At the breakpoint by `debugger()` method, the connection is
needed and wait for the connection if it is not connected.
With the fowllowing scenario, the debugger raises an exception
becuase the connection is kept (but disconnection violate this
assumption)
1. run the script includes `debugger` call
2. connect to DAP client
3. disconnect from DAP client
4. call `debugger` method
To solve this issue, it needs to wait for the connection.
`UI_ServerBase::sock` and `UI_ServerBase::readline` do it and we
can use them on DAP connection, so remove `UI_DAP::sock` and
`UI_DAP::readline`.
=> DAP: need to wait for connection

lib/debug/config.rb, lib/debug/server.rb
Ignore breakpoints if no clients are attached.
=> `ignore_bp`

lib/debug/frame_info.rb, lib/debug/tracer.rb
=> respect `use_short_path` on trace

ext/debug/debug.c, lib/debug/session.rb, lib/debug/thread_client.rb
With pending method breakpoints, track all method invocation to track
`method_added` and `singleton_method_added`.
Of course, this approach slows down the debuggee's performance.
This patch tracks all `method_added` and `singleton_method_added` methods
and further defined such methods for the classes/modules. This approach
doesn't have performance penalty any more.
This patch also fix the message at registering the pending method
breakpoint.
```ruby
binding.b do: 'b C#foo' unless ENV['NO_PENDING_BP']
def fib n
if n<2
n
else
fib(n-1)+fib(n-2)
end
end
require 'benchmark'
Benchmark.bm{|x|
x.report{ fib(35) }
}
```
Results:
```
Without pending breakpoints:
$ NO_PENDING_BP=1 exe/rdbg -n target.rb
user     system      total        real
0.929580   0.000000   0.929580 (  0.929682)
With pending …
```
=> Improve method breakpoint performance.

lib/debug/thread_client.rb
Now method breakpoints accepts `expr.name` and `expr#name`.
And with any `expr` can become a pending method bp.
However, general `expr` in other context does not make sense,
so only `ClassName` style expressions can become pending bps.
They can be activated when the `ClassName#foo` is defined.
=> Only `Class::Name#foo` can become pending bp

exe/rdbg, lib/debug/session.rb, test/console/rdbg_option_test.rb, test/support/console_test_case.rb
=> Fix rdbg's RUBYOPT handling logic

test/support/console_test_case.rb
Tests of snapshot tarball are failed, because the CIs run without write permissions to HOME.
So I want to check the desired feature instead of `ENV["CI"]`.
https://github.com/ruby/actions/runs/7617816773?check_suite_focus=true#step:17:2135
```
Failure: test_frame_filtering_works_with_unexpanded_path_and_expanded_skip_path(DEBUGGER__::BasicBacktraceTest):
Test::Unit::AssertionFailedError: 
--------------------
| Debugger Session |
--------------------
> [1, 2] in /tmp/debug-20220801-16442-89w16l.rb
> =>   1| load "~/foo.rb"
>      2| Foo.new.bar
> =>#0	<main> at /tmp/debug-20220801-16442-89w16l.rb:1
> file = File.open('/home/runner/foo.rb', 'w+') { |f| f.write('class Foo; def bar; debugger; end; end') }
> [?2004h(rdbg) file = File.open('/home/runner/foo.rb', 'w+') { |f| f.write('class …
```
=> Check if HOME can change or not instead of ENV["CI"]

lib/debug/session.rb, test/console/thread_test.rb
This event will be triggered before the new thread even has a `ThreadClient`. So in this case, the `@tc` will be overridden to just `nil`,
which is wrong.
However, we also don't want to just set `@tc` to the new thread's newly created `ThreadClient`. This is because a thread's creation can happen during a subsession, and promptly switching `@tc` to another thread's `ThreadClient` will misfire thread suspension.
Fixes #725
=> Avoid setting @tc in thread_begin event

lib/debug/server_dap.rb
We do the same for `terminate` request too. This makes sure the response and bp cleanup are always performed and avoids flaky testing result.
=> Perform disconnection cleanup and return response before killing debuggee

exe/rdbg
When starting from rdbg, the debug gem is not activated, and cannot find the debug/debug extension library under the gem extensions directory.
As well as `rdbg` passes the path to debug.rb, also the path to the extension library should be passed.
=> Set path to debug.so

lib/debug/client.rb
Fixed typo for the zsh symbol name
=> fix typo for zsh option

test/console/backtrace_test.rb
Do not leave a created file in the home directory after test.
I tried changing home directory in [previous pull request](https://github.com/ruby/debug/pull/732).
But GitHub Actions environment cannot allow to change home directory.
https://github.com/ruby/actions/runs/7843995832?check_suite_focus=true#step:17:3353
```
> eval error: Permission denied @ rb_sysopen - /home/runner/foo.rb
```
So I will try another solution that allow temporarily changing home directory in tests.
And then I found remaining `~/foo.rb`.
https://github.com/ruby/actions/runs/7848993435?check_suite_focus=true#step:19:27
```
+ diff -u /tmp/stat-before-tests.txt /tmp/stat-after-tests.txt
--- /tmp/stat-before-tests.txt	2022-08-16 01:05:14.740220993 +0000
+++ /tmp/stat-after-tests.txt	2022-08-16 01:13:22.767165216 +0000 …
```
=> Remove a created file in test

lib/debug/session.rb
Before setting `@lock_file`, remote client can send stop request to the parent process and it can cause data race issue.
=> fix timing issue

README.md, misc/README.md.erb
=> Update URL example for Chrome in README

lib/debug/session.rb
I have been experiencing an issue where compare path is causing my vscode debugger to be unable to attach. Safe navigating the downcase function seems to have stabilized the issue for me so I figured I would contribute the change back. Without this change I get the following error over and over when attempting to attach to my rails server until I restart the rails server.
```
14:58:51 web.1    | DEBUGGER: Connected.
14:58:51 web.1    | DEBUGGER: ReaderThreadError: undefined method `downcase' for nil:NilClass
14:58:51 web.1    | ["/Users/rbclark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/debug-1.6.2/lib/debug/session.rb:2232:in `compare_path'",
14:58:51 web.1    |  "/Users/rbclark/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/debug-1.6.2/lib/debug/session.rb:1384:in `block in …
```
=> Safe navigate when attempting to compare paths

CONTRIBUTING.md
Just removing the extra ` to get a proper inline code block
=> Fix markdown syntax in CONTRIBUTING for chrome test

test/tool/test_builder.rb
These generators were wrong, as they were inheriting from `TestCase`, but then trying to use `run_<protocol>_scenario`, which is only available in `ProtocolTestCase`
=> 🐛 Fix test generator for protocol tests

test/console/backtrace_test.rb, test/console/rdbg_option_test.rb
This is additional fixes to https://github.com/ruby/debug/pull/768.
It seems that the File.writable? return true on the environment of nightly packaging actions.
In this PR checking permissions by creating the file to be created in advance.
=> check permission errors by creating a file in advance

lib/debug/server_cdp.rb, lib/debug/server_dap.rb, lib/debug/thread_client.rb
This will fix https://github.com/ruby/vscode-rdbg/issues/65
=> use `::Module` for `nesting`

test/tool/test_builder.rb
=> Update test generator directory names to reflect latest changes

lib/debug/server_cdp.rb
=> Support BasicObject in Chrome debugging

test/support/protocol_test_case.rb
The current test framework fails to find a server key when "out" or "input" is included in the key. This may cause an unexpected bug.
=> Correct matching condition when finding a server key

lib/debug/thread_client.rb
When typing “edit” into the debugger, Panic Nova would not wait because it requires the -w flag, and the call to system was not respecting it. This commit uses the Shellwords.split method to separate it into another argument for system so Nova or other editors that require a flag work properly.
=> Resolve #726 Panic Nova Edit Feature

test/support/assertions.rb, test/support/protocol_test_case.rb, test/support/test_case.rb
=> Correct Env name for UI to be tested

lib/debug/server_dap.rb, test/protocol/binary_data_dap_test.rb
This fixes #756
DAP is JSON-based, so the state of all variables is dumped into a string that needs to be unicode. When a variable contains binary data that is NOT unicode, this breaks with: `source sequence is illegal/malformed utf-8`.
This patch makes sure that we can display at least part, and show the user that the data they are seeing is not exactly the one that is in memory.
I tried this in VSCode (which uses DAP), and saw:
1. Before this patch: the debugging session crashes
2. After this patch:
As a side note, `vscode-ruby-debug` doesn't even try to show the variable content and just shows `[Invalid encoding]`, which, IMO, is a worse UX.
=> 🐛 Support displaying variables with non-unicode data

lib/debug/thread_client.rb, test/console/control_flow_commands_test.rb
- `next` can be quite slow when stepping over code. It appears this is a known issue due to expensive calls to [DEBUGGER__.frame_depth](https://github.com/ruby/debug/blob/2cb44483c681f6806bf6843a8f996d3a10d0e42c/ext/debug/debug.c#L95) that are made for every [:line event when stepping](https://github.com/ruby/debug/blob/2cb44483c681f6806bf6843a8f996d3a10d0e42c/lib/debug/thread_client.rb#L327). 
- This check is made to determine if we have returned to the same stack depth as when `next` was called, since that's where we want to break.
- This performance penalty is significant when stepping over code in a large codebase with a large call stack.
- This PR improves the performance of stepping with `next` by restricting when frame_depth is called for `:line` events. 
- By _not_ checking …
=> Faster `next` by reducing number of frame_depth calls

lib/debug/thread_client.rb, test/console/control_flow_commands_test.rb
Reverts ruby/debug#743
It doesn't support multi-threads.
=> Revert "Faster `next` by reducing number of frame_depth calls"

README.md, misc/README.md.erb
Closes https://github.com/ruby/debug/issues/644
=> Add additional resources section and link to migration guide and cheatsheet

lib/debug/server_dap.rb, test/protocol/call_stack_with_skip_dap_test.rb
This makes the DAP implementation respect `skip_path`, to only return frames that are not skipped.
See https://github.com/ruby/debug/issues/748
=> 🐛 Respect skip_path when returning the backtrace in ServerDAP

lib/debug/server_dap.rb
This is a fix for #741
Basically, allow users to specify the `local_fs_map` even when using `UI_UnixDomainServer`. The idea is to maintain the existing behavior when the configuration is not specified, but use it when it is.
From the original context:
Stripe runs `ruby` on a remote server and VS Code on a laptop. We proxy the unix domain socket from server to laptop, and need to use the fs map feature to translate file paths.
=> ✨ Allow setting local_fs_map even when using UI_UnixDomainServer

lib/debug/session.rb, lib/debug/thread_client.rb, test/console/record_test.rb
Currently, `step back <n>` doesn't work in replay mode. This PR fixes it.
=> Enable "step back <n>" while replay

lib/debug/thread_client.rb, test/console/record_test.rb
Currently, `step <n>`doesn't work in replay mode. This PR fixes it.
=> Enable "step <n>" while replay

lib/debug/session.rb, lib/debug/thread_client.rb, test/console/control_flow_commands_test.rb
When `next` command canceled with other breaks, for example, stop
at a breakpoint while executing `next` command, the `next` command
should be canceled and it should not stop on the next line.
However, the current implementation left the TracePoint object for
step commands, so it should be disabled.
=> Disable canceled step/next/finish

lib/debug/session.rb, lib/debug/thread_client.rb, test/console/control_flow_commands_test.rb
`step into <name>` stops at the beggining of the method `<name>`.
`into` is added because there are alreay `step back` and `step reset`
commands.
fix https://github.com/ruby/debug/issues/655
=> `step into <name>`

lib/debug/session.rb
- Calls to `ThreadClient.current.on_load` spend time pushing and popping the :load operation on the event queue, and waiting for the :load event to be handled.
- In a large Rails app with many loads, this extra time results a ~10-20% increase in environment load time when using `require "debug"`, event when there are no breakpoints set at all. This seems to be at odd's with the [README's ](https://github.com/ruby/debug#debugrb) "_Fast: No performance penalty on non-stepping mode and non-breakpoints._"
- By skipping calls to `ThreadClient.current.on_load` when there are no breakpoints present at all, we can save some of this time. 
- As far as I can tell this is safe, as the main responsibility of `ThreadClient.current.on_load` is to handle any pending breakpoints in …
=> Skip check for pending breakpoints if no breakpoints are present

lib/debug/config.rb, lib/debug/server_cdp.rb, lib/debug/server_dap.rb, lib/debug/session.rb, lib/debug/thread_client.rb
As discussed [here](https://github.com/ruby/debug/pull/665#discussion_r911458379), the skipping logic is a global state and isn't related to user configuration. So moving related methods to the top-level `DEBUGGER__` module probably conveys the intention better.
=> Move skipping logic out of Config class

ext/debug/debug.c, ext/debug/extconf.rb, test/console/control_flow_commands_test.rb
- By using [rb_profile_frames](https://github.com/ruby/ruby/blob/d6f21b308bcff03e82f8b3dbf11a852ce111b3b3/include/ruby/debug.h#L51) instead of `rb_make_backtrace` in DEBUGGER__.frame_depth, we can improve the performance of frame_depth substantially for common cases. This leads to much faster `next` and `finish` performance.
- `rb_profile_frames` is notably faster than `rb_make_backtrace` as it returns pointers and does not perform allocations (which rb_make_backtrace does).
- We must set a buffer size for `rb_profile_frames` which we have picked here as 4096. This should cover the vast majority of calls. (i.e. the common stack depth in our large codebase is in the hundreds). There is a fallback to `rb_make_backtrace` to support the very large stack depth cases. 
- Note: it would have …
=> Faster next / finish by using `rb_profile_frames`

lib/debug/breakpoint.rb, lib/debug/session.rb
Using version string is not good manner on Ruby.
Futhermore, `bps_pending_until_load` is added.
=> check `RubyVM.keep_script_lines`

lib/debug/server_dap.rb
attach configuration in launch.json file `"nonstop": true` option
is supported. If nonstop is true, do not pause on attach timing.
fix #739
=> `"nonstop": true` option (default: false) on launch.json

lib/debug/config.rb, lib/debug/session.rb
SessionCommand class represents the session commands attributes.
* repeat: repeat on empty command.
* cancel_auto_continue: cancel auto continue on `source`.
* postmortem: available on postmortem mode.
* unsafe: unsafe command (not supported).
Now only a few commands such as `step`, `next`, ... are
`repeat`able.
Maybe it fixes https://github.com/ruby/debug/issues/764
=> introduce SessionCommand

lib/debug/server.rb, lib/debug/server_cdp.rb, test/support/cdp_utils.rb, test/support/protocol_test_case.rb, test/support/test_case.rb
https://user-images.githubusercontent.com/59436572/197338015-42f0ece1-86eb-42e4-bb19-74ac8ab17408.mov
When node.js users use Chrome DevTools debugging, they open `chrome://inspect`, then click the link on the page and start debugging it.
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27
This PR supports this feature.
1. Execute debugger as a TCP/IP debuggee. `9229` is the default port on the Inspector page in chrome.
```
$ rdbg target.rb -O --port 9229
```
2. Open `chrome://inspect`, then target will be shown up.
3. Click "inspect" and the window will be opened!
=> Allow debugger to be attached from Inspector page in Chrome

lib/debug/server_cdp.rb
https://user-images.githubusercontent.com/59436572/199138098-339ba6e8-1ea1-400d-a3ad-44513ff5f82d.mp4
=> Support opening Chrome automatically on windows

lib/debug/thread_client.rb
This makes the debugger's `irb` command work in the same location as the current frame's location, instead of `"(rdbg)/#{f}"`. With the current implementation, commands like `whereami` don't work. The debugger shouldn't modify the source location for `irb` command.
```rb
$ ruby ~/tmp/a.rb
[1, 3] in ~/tmp/a.rb
1| require 'debug'
=>   2| debugger
3| puts 'hello'
=>#0    <main> at ~/tmp/a.rb:2
(rdbg) irb    # command
irb(main)[01:0]> whereami
The current context doesn't have code.
=> nil
```
It doesn't show the current location, and `whereami` doesn't work.
```rb
$ ruby ~/tmp/a.rb
[1, 3] in ~/tmp/a.rb
1| require 'debug'
=>   2| debugger
3| puts 'hello'
=>#0    <main> at ~/tmp/a.rb:2
(rdbg) irb    # command
From: /home/k0kubun/tmp/a.rb @ line 2 :
1: require 'debug'
=> 2: debugger
3: puts …
```
=> Use binding's location on irb command

lib/debug/server_dap.rb
Long results on DAP was clipped with 4096 chars. This patch shorten
this limit to 180 chars. Compound data structure doesn't have any
issue because expanding the result shows more details with corresponding
values such as instance variables and so on.
The problem is String object because we can not know the whole string body
if it is > 180 chars. To see the whole body this patch provides `#dump`
special field to show the whole body of the string and you can copy&paste
the value.
This patch also introduce `::DEBUGGER__::NaiveString` class. Evaluation
results of instances of this class will not be clipped so if you need to
get whole body of String, please wrap the string with `NaiveString` class.
fix https://github.com/ruby/debug/issues/802
=> DAP: change result chars: 4096 -> 180

lib/debug/server_dap.rb
fix https://github.com/ruby/debug/issues/798
=> DAP: sort by instance variable names

.github/workflows/protocol.yml, .github/workflows/ruby.yml
The version 3.x appears to be due to the following:
- https://github.com/actions/checkout/pull/689
There have been no breaking changes, and we seem to have no problem keeping up with the latest version.
=> Update actions/checkout version to v3

debug.gemspec, lib/debug/thread_client.rb
This implements what's requested at https://github.com/ruby/debug/pull/804#issuecomment-1318958864, using https://github.com/ruby/irb/pull/444.
=> Pass show_code: false to binding.irb if available

lib/debug/breakpoint.rb, lib/debug/thread_client.rb
This PR supports passing `skip_src: true` to `add_line_breakpoint`. 
I'd like to use this from IRB's `debug` command https://github.com/ruby/irb/pull/446 to avoid showing the same source code twice. This is the same feature as https://github.com/ruby/debug/pull/804#issuecomment-1318948072 but the gems in the other way around.
=> Add skip_src option to LineBreakpoint

lib/debug/server_cdp.rb
Recently, random failures such as `Timeout::Error` and `Errno::ECONNREFUSED` have been occurring. The reason for the error in CDP test is that UI_ServerBase::readline is overridden in CDP. continue is executed as a debug command because UI_CDP::readline returns continue if @q_msg is nil. See ono-max#8 for information on how to reproduce the error.
=> CDP: do not override `UI_ServerBase::readline`

test/console/backtrace_test.rb, test/console/break_test.rb, test/console/catch_test.rb, test/console/config_test.rb, test/console/control_flow_commands_test.rb, test/console/debug_statement_test.rb, test/console/delete_test.rb, test/console/display_test.rb, test/console/eval_test.rb, test/console/frame_control_test.rb, test/console/help_test.rb, test/console/info_test.rb, test/console/kill_test.rb, test/console/list_test.rb, test/console/load_test.rb, test/console/quit_test.rb, test/console/rdbg_option_test.rb, test/console/record_test.rb, test/console/trace_test.rb, test/console/watch_test.rb, test/support/console_test_case.rb, test/support/test_case.rb, test/support/test_case_test.rb
Remote debuggee begin to exit when readable stream or writable stream is closed. Thus, tests do not fail even though remote debuggee does not exit after scenarios. We need to close streams after `kill_safely` method.
This needs https://github.com/ruby/debug/pull/817.
=> Make sure to fail when remote debuggee does not exit after scenarios

test/support/protocol_test_case.rb, test/support/protocol_test_case_test.rb
The current test framework for protocol tests checks if remote debuggee is terminated. However, the test framework doesn't check if debuggee is terminated completely. This PR fixes it.
To pass the test, https://github.com/ruby/debug/pull/818 is needed.
=> Make sure to kill remote debuggee in the protocol test

lib/debug/local.rb, lib/debug/server.rb, lib/debug/session.rb, lib/debug/thread_client.rb
`quit` command kills Ruby process with `exit` method on the session
thread. Ruby threads receives `SystemExit` exception, but it doesn't
receive immediately and runs some lines after `quit` command.
This patch exits the process immediately.
Note that on the remote debugging `quit` command doesn't kill the
debuggee process but kills remote client process and debuggee process
continues the running.
`quit` means kills a debugger process and on the local debugging
debuggee process is on the debugger process, so that killing
debugger process kills debuggee process too.
fix #815
=> `quit` command immediately

test/support/test_case_test.rb
`test_the_test_fails_when_the_script_doesnt_have_line_numbers` is sufficient to meet the requirements for local testing only. Also, the test is not stable in remote testing. See https://github.com/ruby/debug/actions/runs/3519789230/jobs/5900091179#step:4:29
=> Disable the test for checking if the target program has line numbers remotely

lib/debug/session.rb
`reset_ui` doesn't activate newly created UI and this patch
fix it.
=> `reset_ui` needs `ui.activate`

README.md, exe/rdbg, lib/debug/config.rb, lib/debug/server.rb, lib/debug/session.rb
`open` conifg
*Deprecate* `open_frontend` and add `open` configuration. It is
consistent with `rdbg --open` option.
`RUBY_DEBUG_OPEN` is also introduced.
For example,
```
$ RUBY_DEBUG_OPEN=true ruby -r debug script.rb
```
opens the debug port remotely.
=> open config

test/support/test_case.rb
Currently, the test on TCP/IP mode sometimes fails because the debugger fails to connect to debuggee. See https://github.com/ruby/debug/actions/runs/3527685026/jobs/5917010231#step:4:338
FYI: The reason why the test has not failed until now is the test framework did not correctly detect that debuggee was terminated. Since the test framework correctly detected it from ruby/debug@6d9f231, the test began to fail, as it did this time.
=> Make sure to wait TCP/IP server to start up

ext/debug/debug.c, ext/debug/extconf.rb
Cancel #746 and use new API from Ruby 3.2 for performance improvement.
=> Use dc depth

lib/debug/thread_client.rb, test/console/control_flow_commands_test.rb
On the code like that:
```ruby
foo; bar
next_line
```
and breaking at the end of `foo`, `next` command moves to the beggining
of `bar`, but it should be `next_line`. This patch solves this issue.
=> fix control flow

lib/debug/session.rb, test/console/debugger_method_test.rb
- rename file name
- support `debugger` method in subsession
=> debugger in subsession

lib/debug/breakpoint.rb, test/console/break_test.rb
If specify the break line on the method definition, it stops at
the beggining of method at called time (don't stop at method
definition timing).
The line check algorithm has a bug and this patch fix it.
=> fix break line check algorithm

lib/debug/server_dap.rb, lib/debug/session.rb
* On the debug console, debug commands can type with `,command`
(ex: `, info`)
* Show welcome message on the debug console.
Now this feature is experimental and `,command` can be changed
in near future.
=> DAP: Allow debug command with `,command`

test/support/assertions_test.rb, test/support/console_test_case.rb, test/support/test_case.rb, test/support/test_case_test.rb
Display an accurate message when the test fails' -m 'Currently, the message when the test fails is overridden by a test that checks if the remote debuggee is terminated. For example, when `assert_line_text` method is failed, the message should be `Expected to include ~ in ~`, but it will be overridden, and the message will be `Expected the remote program to finish ~`. We should not assert in ensure block to prevent the problem.
=> Display an accurate message when the test fails

lib/debug/session.rb, lib/debug/thread_client.rb, test/console/info_test.rb
`info ivars obj` shows the instance variables of `obj`.
Note that this command notation also support `/pattern/` like
`info ivars obj /pattern/` so that we can not show ivars of
Regexp literal objects (but I believe nobody use it).
=> support `info ivars obj`

lib/debug/server_dap.rb
`launch` invokes a debuggee process on the same file system so
we can assume `localfs == true`.
fix https://github.com/ruby/vscode-rdbg/issues/82
=> DAP: `launch` should be `localfs == true`

README.md, lib/debug/config.rb, lib/debug/source_repository.rb, test/console/config_test.rb
Now debugger records actually evaluated source code with (1) `eval`
methods or (2) loaded files.
For (1) sometimes `eval` with existing filename, for example erb,
haml and so on.
For (2) sometimes the contents will be changed after loading
especially on development phase.
`config show_evaledsrc` configuration (default: `false`) controls
which should be shown for the source code:
* true: actually evaluated source code
* false (default): current file system's source code
For the erb, haml etc from files, `false`'s behavior seems nice
so I added this configuration (with `false` default).
=> `config show_evaledsrc`

README.md, misc/README.md.erb
This addition to the README.md demonstrates how to specify multiple commands to run when using `binding.b`.
I didn't think it obvious that you needed to have two semicolons separating the commands (`cmd 1 ;; cmd 2`). The README does not document this which is why I thought I would add it there.  
I've also added an example to demonstrate how you could use `pre` and `do` arguments together to create  a more advanced/useful workflow.
P.S. I wouldn't have known how to do both of the above things if it hadn't been for @st0012 Ruby Kaigi talk on debugging. So Thank You for that!
=> Update README.md to show multiple commands execution using binding.b

lib/debug/session.rb, test/console/daemon_test.rb, test/support/console_test_case.rb
Threads could not be started after Process.daemon since the session server thread was gone.
The session must be activated like fork child processes.
=> Support Process.daemon

lib/debug/thread_client.rb
Configuration with `~/.rdbgrc` it is possible that the `current_frame`
is nil. This patch uses `TOPLEVEL_BINDING` for such cases.
=> use `TOPLEVEL_BINDING` if no binding

lib/debug/config.rb, lib/debug/local.rb, lib/debug/session.rb, lib/debug/start.rb
```ruby
require 'debug'       # no_sigint_hook: true
require 'debug/start' # no_sigint_hook: false
```
In this case SIGINT should be a breakpoint but it was not enabled.
=> support reset `no_sigint_hook` config

lib/debug.rb
With `RUBY_DEBUG_LAZY=1`, `require 'debug'` doesn't start a session
but start when `debugger` method is called (or `require 'debug/start'`
is called).
This feature is experimental.
https://github.com/ruby/debug/issues/797
=> `RUBY_DEBUG_LAZY` boot option

lib/debug/client.rb, lib/debug/server.rb
If there are some debuggee processes open debug ports with
UNIX domain socket, `rdbg -A` client lists possible ports.
This patch add more information (pid, $0) for this list.
=> show more information for UNIX domain sockets

lib/debug/server_cdp.rb, lib/debug/server_dap.rb, lib/debug/thread_client.rb
`rdbg --open` may print deprecation warnings when global variables retrieved by DAP client.
sample code:
```ruby
Warning[:deprecated] = true
p 1
```
sample output:
```console
$ rdbg --open --sock-path=/tmp/rdbg.sock --command -- ruby test.rb
DEBUGGER: Debugger can attach via UNIX domain socket (/tmp/rdbg.sock)
(eval):1: warning: variable $= is no longer effective
1
DEBUGGER: Disconnected.
```
=> suppress warnings about deprecated global variables

lib/debug/server_dap.rb
For String objects, show `#dump` when the String object is long
enough. However, the length of a String is not correct condition
because elimination with `...` is used for long `pp`ed result.
This patch shows `#dump` field if `pp'ed_str.end_with?('...')`
is true.
=> DAP: show `#dump` when pp'ed string is too long

lib/debug/prelude.rb, test/console/debugger_method_test.rb
Fixes #865 as well as adding tests to cover `prelude.rb`.
=> Use stricter check to skip `prelude.rb`

lib/debug/thread_client.rb, test/console/control_flow_commands_test.rb
For the `<internal:...>` files does not have a file and `absolute_path`
is nil, so it is assumed as eval'ed code and `skip_location?` add prefix
`!eval:` to the path name. So it also cheks with this prefix too.
fix https://github.com/ruby/debug/issues/866
=> skip <internal:...> file

README.md, lib/debug/session.rb
Some close backquotes for the `until` command are missing, so the display of `README.md` at GitHub is broken. This PR fixes it.
Thank you.
=> Add missing close backquote

test/console/debugger_local_test.rb
https://bugs.ruby-lang.org/issues/18285#note-38
```
old: undefined local variable or method `foo' for main:Object
new: undefined local variable or method `foo' for main
```
=> Support the new message format of NameError in Ruby 3.3

lib/debug/server_dap.rb
Since Object#send is used https://github.com/ruby/debug/blob/master/lib/debug/server_dap.rb#L456, we need to rename to avoid name conflicts.
=> DAP: use Object#__send__ to avoid name conflicts

test/support/console_test_case.rb
ruby/debug's tests randomly fail due to `Timeout::Error` on ruby/ruby ([example](https://github.com/ruby/ruby/actions/runs/4316853052/jobs/7533177716)). I'd like to increase the timeout to reduce the amount of CI failures.
=> Increase timeout in debug_code

test/console/backtrace_test.rb
Prevents this warning when running the tests:
`debug/test/console/backtrace_test.rb:139: warning: assigned but unused variable - file`
=> Fix warning about unused variable

test/console/color_test.rb
=> Avoid memberless Struct

lib/debug/server_cdp.rb
Methods send_response, send_event and fire_event are checking if the keyword arguments are empty before propagating an empty hash, the same can be accomplished just propagating the original keyword arguments.
=> Always propagate keyword arguments in WebSocketServer

lib/debug/session.rb, test/console/daemon_test.rb
As discussed here:
https://github.com/ruby/debug/commit/699a31e1adfcf51cf4f6f9e84f862e45072f83b4#r94469355
The following repo demonstrates the problem:
https://github.com/andyw8/replicate-debug-daemon-patch-issue
```
% BACKGROUND=1 QUEUE=* bundle exec rake resque:work
rake aborted!
ArgumentError: wrong number of arguments (given 1, expected 0)
/Users/andyw8/.gem/ruby/3.1.1/gems/debug-1.7.1/lib/debug/session.rb:2441:in `daemon'
/Users/andyw8/.gem/ruby/3.1.1/gems/resque-2.4.0/lib/resque/worker.rb:170:in `prepare'
/Users/andyw8/.gem/ruby/3.1.1/gems/resque-2.4.0/lib/resque/tasks.rb:18:in `block (2 levels) in <main>'
```
In this branch, the Gemfile is updated to point to this PR:
https://github.com/andyw8/replicate-debug-daemon-patch-issue/tree/andyw8/fix-process-daemon-patch:
```
% …
```
=> Fix arguments for `::Process::daemon` patch

test/console/info_test.rb
This PR adds tests for #855, which introduced the ability to use `info consts` with an expression. The tests cover a direct constant usage, a constant alias and a method that returns a constant.
=> Add test for info consts with an expression

.github/workflows/ruby-macos.yaml, .github/workflows/ruby.yml
Update CI matrix ruby versions.
- Add 3.2 ✨ 
- ~~Remove 2.6~~ 🔥 
ref: https://www.ruby-lang.org/en/downloads/branches/
```
Ruby 3.2
status: normal maintenance
release date: 2022-12-25
```
```
Ruby 2.6
status: eol
release date: 2018-12-25
EOL date: 2022-04-12
```
=> 🔼 Update CI matrix Ruby versions

lib/debug/server_cdp.rb, test/protocol/eval_test.rb
=> CDP: Support evaluating expression on non-current frame

lib/debug/server.rb, lib/debug/server_cdp.rb
Describe your changes: Improved stability for chrome debugging 
**Display the greeting message regardless of the status of invocation of chrome.**
This allows coming back to the debugger on a new tab when the window process by `UI_CDP.run_new_chrome` is killed.
**Handle `Errno::ESRCH` in `UI_CDP.cleanup_reader`.**
When the process by `UI_CDP.run_new_chrome` is killed, re-killing it breaks your debugging session and in turn the "debugee".
I stumble upon this inconvenience when using it in a rails application, I noticed that after closing the chrome window I couldn't go back to it, and re-attaching with `bin/rdbg -A --open=chrome` gave more cryptic errors.
Also when restarting the app to get a hold of the debugging window, I noticed it throws `Errno::ESRCH`.
These changes should address the …
=> Improved stability for chrome debugging

lib/debug/session.rb
fix https://github.com/ruby/debug/issues/899
=> free terminated ThreadClients

lib/debug/server_dap.rb, test/support/protocol_test_case.rb
When debug.gem tries to send response from multiple threads, the socket connection is closed. I confirmed this bug when using custom request from vscode-rdbg.
Also, because Errno::EPIPE is rescued while sending message to socket, protocol_test_case_test.rb did not pass. protocol_test_case_test.rb had been passed because ReaderThreadError was occurred and the debuggee process was still alive. Here is a scenario. After closing socket, terminated event was sent. However socket was closed, so debuggee process raised Errno::EPIPE and debugggee process was still alive. The test framework detected the status and failed.
Thus I fixed so that the test framework does not kill the debuggee process unexpectedly.
=> DAP: use Mutex when sending response

lib/debug/session.rb
`@session_server` should be assigned at first.
`@session_server = Thread.current` in the session thread does not
work because the creator thread can access to `@session_server`
before it.
=> Fix timing bug on session_server creation

lib/debug/server_cdp.rb, lib/debug/server_dap.rb, lib/debug/source_repository.rb, test/support/protocol_test_case.rb, test/support/test_case.rb, test/tool/test_builder.rb
Found by running `rubocop --only=Lint/UselessAssignment`
=> Fix useless assignments

lib/debug/tracer.rb
All tracers use `#out` for printing output, which doesn't use `puts` either. So `Tracer#puts` is never called and can be removed.
=> Remove Tracer#puts as it's not used

test/support/protocol_test_case.rb, test/support/protocol_test_case_test.rb
When assertions failed, we should let the AssertionFailedError surface and not calling flunk so we can get correct failure messages.
Assume we have this test that fails the assertion:
```rb
run_protocol_scenario PROGRAM do
req_add_breakpoint 5
req_continue
assert_repl_result({value: '5', type: 'Integer'}, '1+2') 
req_terminate_debuggee
end
```
**Before**
The failure message is completely overridden by [this flunk call](https://github.com/ruby/debug/blob/master/test/support/protocol_test_case.rb#L371) and becomes misleading.
```
-------------------
| Failure Message |
-------------------
Expected the debuggee program to finish.
/Users/hung-wulo/src/github.com/ruby/debug/test/support/assertions.rb:97:in `assert_block'
/Users/hung-wulo/src/github.com/ruby/debug/test/support/protocol_test_case …
```
=> Avoid raising debuggee not finished error if assertions failed

lib/debug/server_dap.rb
This PR is for https://github.com/ruby/debug/pull/935.
=> DAP: allow custom request extension in ThreadClient class

lib/debug/server_dap.rb
We'll introduce a new feature Rdbg Record Inspector. We can use record and replay debugging in VS Code.
https://user-images.githubusercontent.com/59436572/226538815-4cf4484c-8413-4b74-b5f1-b335ba99b0b4.mov
1. Click on "Start Record" in RECORD AND REPLAY view
2. Execute the program
That's it! You can go back to some points by clicking the trace log.
=> DAP: introduce Rdbg Record Inspector

lib/debug/config.rb
to pass on the Windows.
fix https://github.com/ruby/vscode-rdbg/issues/169
=> relax authority check

test/protocol/variables_test.rb, test/support/protocol_test_case.rb
This PR adds tests for the following PRs:
- #835
- #806 
They both rely on @vinistock's addition of the `gather_variables` method extract the behavior of collecting variables.
This method is explained in a comment from #884:
> To avoid having to assert every single global variable using an array (which is a big number considering Ruby's built in globals), I extracted part of assert_locals_result into gather_variables, so that we can get all available globals in the test and just verify a few of them.
=> Add tests for various variable features

lib/debug/server_cdp.rb, lib/debug/server_dap.rb, lib/debug/session.rb
From ThreadClient it retunrs `:dap_result` or `:cdp_result` to the SESSION.
This patch renames it to `:protocol_result` and it will be handled
by `process_protocol_result`.
=> dap/cdp_result -> protocol_result

.github/workflows/test_test.yml, Rakefile, test/support/assertions_test.rb, test/support/protocol_test_case_test.rb, test/support/test_case_test.rb
- separate 'test_console' and 'test_test'
- Omit slow tests for healty CI
I hope https://github.com/ruby/debug/pull/933 will fix.
=> skip slow tests

lib/debug/server_dap.rb
Follow up for ruby/debug#939
Change the name from "request_..." to "custom_dap_request_" in UI_DAP and ThreadClient for consistency
=> DAP: rename the method name of custom request

lib/debug/breakpoint.rb, lib/debug/server_dap.rb, lib/debug/session.rb, lib/debug/source_repository.rb, test/console/break_test.rb
Breakpoints should be remained on reloaded files. To make sure
maintaining loaded file names.
fix https://github.com/ruby/debug/issues/870
=> remain breakpoints on reloaded files

test/support/console_test_case.rb, test/support/protocol_test_case.rb, test/support/test_case.rb
1. `remote_info.failed_process` stores symbol but we only use the value's presence to check if the process is force-killed.
2. The force-killed status is directly controlled by `kill_safely` through `kill_remote_debuggee`, which is directly called right before we check the status with `remote_info.failed_process`.
Combining the two, we can just let `kill_safely` and `kill_remote_debuggee` return the force-killed status and not storing it in `remote_info`, which already contains a bunch of information.
This also eliminates the need to pass `test_info` to `kill_safely`, which makes related code easier to understand and maintain.
=> Improve test process' kill signalling

lib/debug/server_dap.rb
The generated result in ThreadClient is passed as "result". We usually use it when returning responses to VS Code in Session class
=> Add "result" as an argument to custom_dap_request_event method

lib/debug/session.rb, lib/debug/thread_client.rb, test/console/eval_test.rb
When a thread keeps a lock, and REPL runs a code which needs the
lock, other threads should make a progress to release the lock.
fix https://github.com/ruby/debug/issues/877
=> restart all threads on eval

lib/debug/config.rb
Without this patch, `rdbg -v target.rb` prints version and terminates
the process. With this pach, `-v` prints version and starts debugging
for `target.rb`.
If no filename is given, terminates the process.
=> `-v` prints version and do something

lib/debug/server_dap.rb, test/protocol/eval_test.rb
This makes sure DAP evaluation request also doesn't hang.
See #947 for the original console implementation.
=> Restart threads on DAP evaluation

lib/debug/server_cdp.rb, test/protocol/break_raw_cdp_test.rb, test/protocol/call_stack_raw_cdp_test.rb, test/protocol/catch_raw_cdp_test.rb, test/protocol/hover_raw_cdp_test.rb, test/protocol/next_raw_cdp_test.rb, test/protocol/step_raw_cdp_test.rb, test/protocol/watch_raw_cdp_test.rb
This change improves the performance in Chrome Debugging
We do not have to send "Debugger.scriptParsed" when the path is known
=> CDP: send "Debugger.scriptParsed" only when a new file path is found

test/support/assertions_test.rb, test/support/console_test_case.rb, test/support/protocol_test_case.rb, test/support/protocol_test_case_test.rb, test/support/test_case.rb
If AssertionFailedError occurs, we can send signals soon without waiting first.
=> Kill a debuggee process fastly if a test fails

test/support/protocol_test_case.rb
Currently, we have a random failure such as Errno::ECONNRESET in the test for attaching to cdp server(FYI: https://github.com/ruby/debug/actions/runs/4588502898/jobs/8102758399\?pr\=955). We need to retry connecting when Errno::ECONNRESET occurs.
=> Retry connecting in test for attaching to CDP server

lib/debug/session.rb
Currently, `exnted_feature` method is defined outside of Session class. This PR fixes it.
=> Move `Session#exnted_feature` into Session class

test/protocol/eval_test.rb, test/support/protocol_test_case.rb
The current implementation doesn't work when the result is a boolean type because the helper calls `#inspect` on the values of `JAVASCRIPT_TYPE_TO_CLASS_MAPS`, which is an array for boolean types.
Example failure:
```
<["[TrueClass, FalseClass]"]> was expected to include
<"FalseClass">.
```
Since `JAVASCRIPT_TYPE_TO_CLASS_MAPS` is never used in other places, we can just store the String representation of the class name in the hash and avoid calling `#inspect` on the values.
=> Improve assert_repl_result for CDP

lib/debug/server_dap.rb
Fixes typo `lengthddsfsd`
Relates to https://github.com/ruby/debug/pull/869
=> Fixes typo `lengthddsfsd`

lib/debug/dap_custom/traceInspector.rb, lib/debug/frame_info.rb, lib/debug/server_dap.rb, lib/debug/thread_client.rb, test/protocol/rdbgTraceInspctor_test.rb, test/support/protocol_test_case.rb
We introduce Rdbg Trace Inspector. This is useful when tracing in VS Code. Users can search tracing logs easily and get a lot of useful information by using Rdbg Trace Inspector. For example, users can know which method is called, which line is executed, local variables at some point, and so on.
1. Click on "Start Trace" in TRACE INSPECTOR view
2. Execute the program
That's it! You can check the location and returned value by clicking the trace log.
Users can know which method is called, its parameters, and return values.
https://user-images.githubusercontent.com/59436572/232519376-f6970c81-90d9-4312-9b0e-b76bfe2ebff2.mov
This is slow, but Users can get a wealth of information by enabling Record & Replay. For example, users can know the backtrace and local variables during the execution. …
=> DAP: introduce Rdbg Trace Inspector

lib/debug/dap_custom/traceInspector.rb
`undefined method `dropped_trace_cnt` for nil:NilClass` occurs when @recorder is nil. This PR fixes it
=> DAP: Access `dropped_trace_cnt` only when `@recorder` is not nil

test/console/control_flow_commands_test.rb
I have a plan to remove `ext/readline` that is GNU Readline wrapper from Ruby 3.3.
But `test_finish_0` is failing with Ubuntu environment. see https://github.com/ruby/ruby/pull/7781#issuecomment-1530907496.
I'm not sure why `fin 0` is failed with its environment. It may be issue of `Reline`. 
1. Use Ubuntu environment.
2. Checking out [`hsbt:extract-ext-readline` branch](https://github.com/hsbt/ruby/tree/extract-ext-readline).
3. `./configure`, `make ruby && make up && make && make test-bundled-gems`
/cc @ruby/irb-reline
=> Omit test_finish_0 because it failed with only reline environment

lib/debug/server_dap.rb, lib/debug/thread_client.rb, test/protocol/variables_test.rb
It is possible to override the `name` method in a class with a method that has arguments, resulting in an `ArgumentError` when calling `klass.name`. #790 addresses this by handing the exception and setting the variable's `type` to `"<Error: #{e.message} (#{e.backtrace.first}>"`.
This PR improves the handling of the case where the `class` method is overwritten and removes the need for the `type_name` method by using `M_NAME.bind_call(klass)` instead of calling the `name` method. Instead of the variable's type being the error message, it is now more accurate:
```
{
"name": "f",
"value": "#<Foo:0x00000001090377a8>",
"type": "<Error: wrong number of arguments (given 0, expected 1) (/var/folders/lf/pp4810hd7n5d0c_zs0skjxfh0000gn/T/debug-20230329-68605-bb7wh3.rb:5:in `to_s'>", …
```
=> Improve variable type name request

lib/debug/thread_client.rb, test/console/info_test.rb
Currently, the command `info c <exp>` crashes the debugger when `<exp>` is not a constant because it raises an exception. This patch fixes it by changing it to `puts`.
**Before**
```
(rdbg) info c foo    # command
nil
#<RuntimeError: nil (by foo) is not a Module.>
@@@ #<Thread:0x000000010308b138 run>
> /Users/hung-wulo/src/github.com/ruby/debug/lib/debug/thread_client.rb:1237:in `backtrace'
> /Users/hung-wulo/src/github.com/ruby/debug/lib/debug/thread_client.rb:1237:in `block in wait_next_action_'
> /Users/hung-wulo/src/github.com/ruby/debug/lib/debug/thread_client.rb:1235:in `each'
> /Users/hung-wulo/src/github.com/ruby/debug/lib/debug/thread_client.rb:1235:in `rescue in wait_next_action_'
> /Users/hung-wulo/src/github.com/ruby/debug/lib/debug/thread_client.rb:1230:in `wait_next_action_' …
```
=> Fix `info c <exp>` when <exp> doesn't return a constant

lib/debug/server_dap.rb, test/protocol/variables_test.rb
* use `M_NAME` to call `Module#name`
* use parens to avoid warnings: `warning: ambiguity between regexp and two divisions...`
=> follow-up #957

test/support/console_test_case.rb
Currently the test framework waits 15 seconds and then terminates if a test fails. The reason for waiting 15 seconds is `kill_remote_debuggee` is called without raising `Test::Unit::AssertionFailedError`. We need to raise `Test::Unit::AssertionFailedError` on all modes when a test fails.
=> Terminate a test early when it fails

lib/debug/session.rb
In the following code, [Signal.#trap](https://docs.ruby-lang.org/ja/latest/method/Signal/m/trap.html) method is overridden.
https://github.com/ruby/debug/blob/v1.7.2/lib/debug/session.rb#L2520
Although the original trap code can accept Integer, the above can't.
That's why I enabled trap function accept Integer(Non-String).
Relates to https://github.com/ruby/debug/issues/975
=> Enable trap function accept Integer(Non-String)

lib/debug/session.rb, test/console/trap_test.rb
follow up for https://github.com/ruby/debug/pull/976
=> work correctly with trap(Integer,...)

lib/debug/server_dap.rb, test/protocol/rdbgTraceInspctor_test.rb
for future extensions.
And rename:
* `load_rdbgExtension` -> `load_extensions`
* `config.rdbgExtension` -> `config.rdbgExtensions`
=> DAP: support `config.rdbgInitialScripts`

test/console/backtrace_test.rb
I rewrote `Integer#times` in Ruby https://github.com/ruby/ruby/pull/8388, so this test needs to use another method.
=> Stop assuming Integer#times is written in C

debug.gemspec
Reline 0.3.8's removal of `timeout` usages has been proven to avoid the frozen issues mentioned in #877, #934, and #1000. So I think it's better to require this version of Reline onwards.
=> Require Reline 0.3.8+ to avoid frozen issue

lib/debug/console.rb
When you enter `1` and then `OPTION+ENTER`, rdbg will crash.
```
[tomoya.ishida:debug]% echo debugger > a.rb
[tomoya.ishida:debug]% rdbg a.rb
[1, 1] in a.rb
=>   1| debugger
=>#0	<main> at a.rb:1
(ruby) 1
#<Thread:0x000000011093fc90@DEBUGGER__::SESSION@server /Users/tomoya.ishida/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/debug-1.8.0/lib/debug/session.rb:179 run> terminated with exception (report_on_exception is true):
/Users/tomoya.ishida/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/reline-0.3.7/lib/reline/line_editor.rb:1131:in `+': TypeError
from /Users/tomoya.ishida/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/reline-0.3.7/lib/reline/line_editor.rb:1131:in `render_partial'
from /Users/tomoya.ishida/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/reline-0.3.7/lib/reline/line_edit …
```
=> Fix prompt list size and colorized code line size to match input line size passed to Reline

lib/debug/session.rb, test/console/break_test.rb
We're currently not invoking `bp.disable` or `bp.delete` on the cloned breakpoint. This means that the associated trace point event continues to be enabled.
Most of the time, that's not an issue because the target `@iseq` will not match. But there are some cases where old `@iseq` objects may continue to exist and we will continue having the execution suspended by the old trace point.
One example scenario of this is when using aliases, which hold references to the old `@iseq` (see the test, which reproduces the issue).
Depending on the order of events, this sometimes leads to execution being suspended by breakpoints that were already removed - because the trace point event is still enabled, even if the breakpoint was removed from the hash. Disabling the trace point for the removed …
=> Disable cloned breakpoints trace point events

lib/debug/session.rb, lib/debug/thread_client.rb
This fixes the following Ruby warnings:
```
lib/ruby/gems/3.2.0/gems/debug-1.8.0/lib/debug/session.rb:2527: warning: assigned but unused variable - sym
lib/ruby/gems/3.2.0/gems/debug-1.8.0/lib/debug/thread_client.rb:618: warning: assigned but unused variable - e
```
=> Fix ruby warnings

test/console/control_flow_commands_test.rb
I fixed a typo in `test/console/control_flow_commands_test.rb`.
environeent -> environment
=> Fix a typo

lib/debug/session.rb
Follow up for #977. 
Update `trap` to avoid assigning to an unused variable `sym` and resolve the warning 
`warning: assigned but unused variable - sym`
=> Update `TrapInterceptor` to avoid assigning to an unused variable

lib/debug/console.rb
The original issue in Reline has been fixed in https://github.com/ruby/reline/pull/358 and was released in Reline 0.2.8+.
Consider `debug` currently requires Reline 0.3.8+, we won't need this patch anymore.
=> Drop patch for Reline 0.2.7

lib/debug/server_dap.rb, test/protocol/break_test.rb
This avoids the TracePoint conflict with Zeitwerk, which was reported in https://github.com/ruby/debug/issues/408. But the fix was not implemented in the DAP server.
=> Allow TracePoint reentry during DAP's evaluation

lib/debug/server_cdp.rb
In order to enable the debugger in Chrome DevTools, it is now mandatory to include the 'debuggerId' field in the RETURN OBJECT of the Debugger.enable method. You can find more information about this change on this PR: https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4774406. This PR addresses this requirement.
=> CDP: Add debuggerId field in the RETURN OBJECT of "Debugger.enable"

lib/debug/server.rb, lib/debug/server_cdp.rb
We are currently facing an issue where the JavaScript engine-based autocompletion appears in the Console panel even when debugging a Ruby program. Unfortunately, we couldn't disable this autocompletion since it's feature implemented directly in Chrome DevTools frontend. 
After a lengthy effort, I have managed to introduce a new option called `noJavaScriptCompletion=true`, which disables the JavaScript engine-based autocompletion. If you're interested in the technical details, you can find more information at the following:
[Chromium Review - devtools/devtools-frontend](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/4063096)
[Chromium Dashboard Commit](https://chromiumdash.appspot.com/commit/7be0efc5865928066550f47b0b3805cd00a2cd7e)"
=> CDP: disable JavaScript engine based autocompletion

lib/debug/session.rb, test/console/info_test.rb, test/console/outline_test.rb, test/console/trace_test.rb
There are several commands that evaluate objects and call methods on them, such as:
- info
- ls (outline)
- trace object
- display
If the called method acquires a mutex shared with another thread (e.g. when using Timeout), then it'd cause a deadlock as all threads are stopped.
For example, if there's an ActiveRecord Relation object stored as a local variable, and the user runs the `info` command, then it'd call `inspect` on it and trigger a database query, it could cause a deadlock as described in #877.
This commit fixes the issue by unfreezing all threads before evaluating those commands and freezing them again after receiving the result event.
Note: theoretically there are more commands that evaluate user program's objects, like `break Foo#bar` calls `Foo.instance_method`. But in that …
=> Unfreeze threads for some object-evaluating commands

.github/workflows/protocol.yml, .github/workflows/ruby.yml, README.md, debug.gemspec, lib/debug/client.rb, lib/debug/config.rb, lib/debug/session.rb, lib/debug/thread_client.rb, test/support/console_test_case.rb
If there is only one opening debug port with UNIX domain socket, no need to use HEAD request.
Before:
```
$ exe/rdbg -O target.rb
DEBUGGER: Debugger can attach via UNIX domain socket (/run/user/1000/ruby-debug-ko1-223816)
DEBUGGER: GreetingError: HEAD request
DEBUGGER: Disconnected.
```
After:
```
$ exe/rdbg -O target.rb
DEBUGGER: Debugger can attach via UNIX domain socket (/run/user/1000/ruby-debug-ko1-223984)
```
=> Do not use HEAD request if 1 port

README.md, lib/debug/config.rb, test/console/client_test.rb
to allow multiple debug sessions.
Now session name is used to name UNIX domain socket file name.
```
$ exe/rdbg -O target.rb --session-name=hoge
DEBUGGER: Debugger can attach via UNIX domain socket (/run/user/1000/rdbg-230122-hoge)
```
```
$ RUBY_DEBUG_SESSION_NAME=fuga exe/rdbg -O target.rb
DEBUGGER: Debugger can attach via UNIX domain socket (/run/user/1000/rdbg-230150-fuga)
```
Co-authored-by: Andy Jeffries <andy@andyjeffries.co.uk>
This PR is rewritten of #1017
=> `session_name` config

lib/debug/session.rb, test/console/backtrace_test.rb
In https://github.com/ruby/debug/commit/3255b7124a0abe20c780f5ae7fba11c3ff690de3, many commands were changed to unfreeze threads to prevent the debugger from hanging. However, the same can occur when running `backtrace`.
Under the hood, it invokes `inspect`, which may trigger Active Record queries, which could be gated by a timeout thread - ultimately causing the debugger to hang forever.
This PR just ensures that threads are restarted for the backtrace command, so that we never get into a situation where the debugger is stuck.
=> Prevent backtrace from hanging if objects in the backtrace use Thread in inspect

lib/debug/server.rb
On HEAD request and attaching, show session name if available.
=> Show session_name on connection

.github/workflows/protocol.yml, .github/workflows/ruby-macos.yaml, .github/workflows/ruby.yml, .github/workflows/test_test.yml, .github/workflows/truffleruby.yml, ext/debug/debug.c, ext/debug/extconf.rb, ext/debug/iseq_collector.c, lib/debug/session.rb, lib/debug/source_repository.rb
Compile iseq_collector.c logic only on CRuby
* iseq_collector.c relies on many CRuby internals, there is no point to compile it on other Rubies.
* It now fails to compile on TruffleRuby:
```
../../../../ext/debug/iseq_collector.c: In function ‘imemo_type’:
../../../../ext/debug/iseq_collector.c:18:13: error: implicit declaration of function ‘RBASIC’ [-Werror=implicit-function-declaration]
18 |     return (RBASIC(imemo)->flags >> FL_USHIFT) & imemo_mask;
|            ^~~~~~
```
See for example this GH action run: https://github.com/ruby/irb/actions/runs/7017641177/job/19091354167?pr=790#step:3:87
I also added a workflow to ensure the extension keeps building fine on TruffleRuby, and cleaned up a bit existing workflows.
=> Compile iseq_collector.c logic only on CRuby

.github/workflows/protocol.yml, .github/workflows/ruby.yml, README.md, debug.gemspec, lib/debug/config.rb, lib/debug/irb_integration.rb, lib/debug/session.rb, lib/debug/thread_client.rb, misc/README.md.erb, test/console/irb_test.rb, test/support/console_test_case.rb
Currently, the `irb` command always opens up a fresh IRB session, which means:
- Users won't have access to `debug`'s commands in this mode.
- To use `debug` commands, users need to leave the IRB session first, which means losing IRB commands or feature like multi-line input.
- Moving between the 2 modes is not practical and doesn't provide a good experience.
So in this PR, I enhanced the `irb` command by making it activate IRB's new [`irb:debug` integration](https://github.com/ruby/irb#debugging-with-irb). 
And if users want to always activate the new IRB console, without constantly typing `irb` command manually, they can achieve this by setting `CONFIG[:irb_console]` to `true`.
Closes https://github.com/ruby/irb/issues/712
When the new `irb` command is executed, it will:
- Open a new …
=> Support IRB console

lib/debug/thread_client.rb, test/support/cdp_utils.rb, test/support/dap_utils.rb, test/support/protocol_test_case.rb, test/support/test_case.rb
This is a first pass at improving the compatibility with the fiber scheduler and contains two changes:
- Ensure the `ThreadClient` is actually per-thread and not per-fiber.
- Ensure that waiting for events (blocking) is done in a blocking context, otherwise it will be redirected in the fiber scheduler which is probably not desirable.
It only works on 3.2 but could be made to work on 3.0 and 3.1 if some tests were changed.
`Fiber.blocking{...}` was introduced in Ruby 3.2. It can be emulated by `Fiber.new(blocking: true) {...}` but the backtrace is changed. This causes some test failures.
My personal opinion is that we can ignore 3.0 and 3.1 but there is an option to support them with the compatibility wrapper outlined above, if we are willing to change some of the tests that check …
=> Fix compatibility with Fiber Scheduler.

lib/debug/session.rb, test/console/rdbg_option_test.rb
=> support Ruby 3.3

ext/debug/debug.c, test/console/nested_break_test.rb, test/support/console_test_case.rb
fix bt on nested break points
`di_body()` doesn't filter C locations so some additional locations were available.
=> Fix BT on nested break

test/console/backtrace_test.rb, test/console/break_test.rb
Same as https://github.com/ruby/debug/pull/1015, but for `Array#each`.
We're thinking of rewriting it in Ruby, and I'd like to avoid failing on test-bundled-gems in the PR.
=> Stop assuming Array#each is written in C

lib/debug/prelude.rb
Using round parens is shell execution.
=> Fix prelude doc example to use curly braces

debug.gemspec
Since Ruby 3.3.0, RubyGems and Bundler warn if users do require the gems that will become the bundled gems in the future version of Ruby. 
https://www.ruby-lang.org/en/news/2023/12/25/ruby-3-3-0-released/
`debug` uses one of those gems, `base64`.
https://github.com/ruby/debug/blob/c82c58044e3881e3c17852e398c3ef8e8aa72936/lib/debug/server_cdp.rb#L5
So if a user use `debug` gem with Chrome, a user will get the warning about that.
```
$ bundle exec rdbg --open=chrome main.rb
/home/y-yagi/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/debug-1.9.1/lib/debug/server_cdp.rb:5: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of debug-1.9.1 to add base64 into its …
```
=> Add `base64` gem to the dependencies

test/console/debugger_local_test.rb, test/console/info_test.rb
https://bugs.ruby-lang.org/issues/16495
This change is same as https://github.com/ruby/bigdecimal/pull/286
=> Support Ruby 3.4's new error message format

lib/debug/thread_client.rb, test/protocol/boot_config_raw_dap_test.rb, test/protocol/threads_test.rb
* should use `base_label` instead of `label`.
* should accept both backtick or single quote
* should accept with class name
=> catch up ruby 3.4.0 error related changes

lib/debug/server_cdp.rb
```
$ ruby -W -c lib/debug/server_cdp.rb
lib/debug/server_cdp.rb:134: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
lib/debug/server_cdp.rb:161: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
lib/debug/server_cdp.rb:193: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
lib/debug/server_cdp.rb:300: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
lib/debug/server_cdp.rb:381: warning: ambiguity between regexp and two divisions: wrap regexp in parentheses or add a space after `/' operator
lib/debug/server_cdp.rb:661: warning: …
```
=> Fix syntax warnings

debug.gemspec, lib/debug/server_cdp.rb, test/support/protocol_test_case.rb
#1066 added `base64` as a dependency to silence warnings under Ruby 3.3
The digest gem already comes with its own base64 method. Just use that and drop the base64 gem dependency.
These methods are equivalent:
https://github.com/ruby/digest/blob/d39b684f9131186b994639be0e324e854eae4b1d/lib/digest.rb#L55-L57
https://github.com/ruby/base64/blob/9669a7d3b0e3b9a739969404daf58f912c58c6b3/lib/base64.rb#L273-L275
=> Drop base64 dependency

lib/debug/console.rb
*Update* -- I believe this error has nothing to do with Rails, but was exposed because my version of Ruby 3.3 did not have readline built properly. When readline could not be loaded, it falls back to the code which calls `gets`, and if there is a filename in ARGV, it will try to load that file as input to `rdbg`. I think the fix remains -- it's the same as https://github.com/ruby/debug/issues/156
A simple way to replicate it would be to move `readline.so` out of the way in your local ruby installation, and then with the programm in `test.rb`:
```ruby
require 'debug'
debugger
```
then run this _ensuring there's a file path in ARGV_, e.g. `ruby test.rb`. This should hit the error.
*Further update* -- I think this may ultimately be because the `readline-ext` gem is no longer bundled as of …
=> Fix ENOENT error when readline is not loaded

test/console/irb_test.rb
`irb_test.rb` will refer IRB configuration like `.irbrc` or something from User's environment. I always got test failure about them. This is my `.irbrc`.
```
IRB.conf.update(
:SAVE_HISTORY => 10000,
:HISTORY_FILE => File.join(ENV["XDG_DATA_HOME"], "irb", "history"),
:PROMPT_MODE => :SIMPLE,
:LOAD_MODULES => ['irb/completion', 'active_support/all'],
:USE_MULTILINE => true,
)
```
See the following result from `make test-bundled-gems`.
```
Failure: test_irb_command_switches_console_to_irb(DEBUGGER__::IrbTest):
--------------------
| Debugger Session |
--------------------
> [1, 2] in /var/folders/_z/1_hsk6zx07v57yg5wlsjxvc80000gn/T/debug-20240122-96632-yvf6i8.rb
> =>   1| a = 1
>      2| b = 2
> =>#0        <main> at /var/folders/_z/1_hsk6zx07v57yg5wlsjxvc80000gn/T/debug-20240122-96632-yvf6i8 …
```
=> Remove and Restore irb configuration like irbrc while irb console tests

.github/workflows/protocol.yml, .github/workflows/ruby-macos.yaml, .github/workflows/ruby.yml, .github/workflows/test_test.yml
This PR use ruby/actions workflow for ruby versions
=> Use ruby/actions workflow for ruby versions

.github/workflows/protocol.yml, .github/workflows/ruby-macos.yaml, .github/workflows/ruby.yml, .github/workflows/test_test.yml
In most cases, we prefer to see the test results rather than setup logs. Therefore, separating setup and execution steps would enhance readability.
=> Separate setup and execution steps in CI

test/protocol/catch_test.rb, test/protocol/eval_test.rb, test/support/protocol_test_case.rb
Sometimes, the "test_response_returns_correct_threads_info" test failed with the following issue: 
https://github.com/ruby/debug/actions/runs/7971483036/job/21761265508#step:4:24
https://github.com/ruby/debug/actions/runs/7971521581/job/21761395380#step:4:24
The program did not pause at the breakpoint when the assert_threads_result method was called. Therefore, it's necessary to ensure that the program pauses after the "req_continue" method is invoked. This PR addresses and resolves the issue.
The above things are reported by @ko1-san. I appreciate for his help.
=> Fix flakey test "test_reponse_returns_correct_threads_info"

ext/debug/debug.c
Using DATA_PTR is internal implementation details so we should not use it.
It should fix this issue: https://github.com/ruby/ruby/pull/10336#issuecomment-2021861692
=> Use rb_iseqw_to_iseq to get iseq pointer

lib/debug/thread_client.rb
`$FILENAME` is unsafe to include in the globals because it modifies ARGV and raises an error if it's a file that does not exist. This causes two issues if rdbg used to debug a command with arguments:
* when using rdbg the server will crash when running `info globals`, as it does not catch the error
* the DAP server catches this error, so when using a DAP client that requests globals before the debugged program was able to handle its arguments then the ARGV changes and the program will not do what's expected
=> do not include `$FILENAME` in globals

test/console/print_test.rb
`Hash#inspect` is proposed to change to `{key: value, non_symbol_key => value}` in https://bugs.ruby-lang.org/issues/20433#note-10
This pull request fixes `test/console/print_test.rb` to pass in both `Hash#inspect` style.
Pull request that change Hash#inspect is here https://github.com/ruby/ruby/pull/10924
=> Accept colon style Hash#inspect in test/console/print_test.rb

test/console/catch_test.rb
"1234" is too short and may be included in tempfile paths.
https://github.com/ruby/ruby/actions/runs/10659931295/job/29543206549?pr=11529#step:13:369
```
Expected not to include `/1234/` in
(
[1, 5] in /var/folders/m4/5dz5h26x329cqq4fx333f8gm0000gn/T/debug-20240902-41234-6fxkst.rb
1| a = 1
2| b = 2
3| 
4| 1/0 rescue nil
=>   5| binding.b
=>#0	<main> at /var/folders/m4/5dz5h26x329cqq4fx333f8gm0000gn/T/debug-20240902-41234-6fxkst.rb:5
)
on LOCAL mode.
```
=> Fix flaky tests

debug.gemspec
Supported here: https://guides.rubygems.org/specification-reference/#metadata Useful for running https://github.com/MaximeD/gem_updater
=> Add changelog_uri to gemspec

README.md, misc/README.md.erb
Minor README updates that threw me off while reading.
=> Fix minor typos / grammar in README.md

test/console/irb_test.rb
After changing IRB's behavior with TERM=dumb in https://github.com/ruby/irb/pull/907, `test_irb_command_switches_console_to_irb` and `test_irb_console_config_activates_irb` began failing. This pull request fixes it.
With a workaround https://github.com/ruby/irb/pull/943, test does not fail now.
As described in `def assert_raw_line_text` comment, assert_line_text is not suitable for testing IRB's prompt.
```ruby
def assert_raw_line_text(expectation)
```
The test was passing before because Reline prints redundant output when TERM is set to dumb, which was problematic while running IRB in emacs shell.
=> Fix irb_test prompt assertion failure

test/support/console_test_case.rb
When debugging the issue related to https://github.com/ruby/irb/pull/919, I noticed that debugger tests don't respect the IRB version I specified in the Gemfile. This is because console tests force override the RUBYOPT env, which will remove the `-rbundler/setup` injected by bundler.
Additionally, if tests use `run_rdbg` with the `rubyopt` option, the RUBYOPT will be overridden yet again.
So in this commit I did 2 improvements:
1. `run_rdbg` should append instead of override RUBYOPT
2. If tests are executed with bundler, we also run the debugger in PTY process with bundler by appending `-rbundler/setup` to RUBYOPT
=> Improve RUBYOPT's handling in tests

README.md, lib/debug/config.rb, lib/debug/server.rb, misc/README.md.erb
Add option to try to connect to a range of TCP ports
Fixes: #368 
Fixes: #1117
We can set an integer value with `--port-range` or `RUBY_DEBUG_PORT_RANGE` in addition to setting a TCP port for remote debugging. When `port` is unavailable, `rdbg` will try to open `port + 1`, `port + 2`, etc. until it finds a suitable port, or reaches the length of the range. This makes it possible to remote debug multiple debuggees in a multithreaded environment, but still use TCP ports in a determined way.
=> Add option to try to connect to a range of TCP ports

lib/debug/server.rb, test/support/test_case.rb
=> `port_range` lvar is not defined

lib/debug/session.rb
When running the `eval` command (or its alias, `call`) without an argument, you get the following error:
```
[REPL ERROR] #<NameError: undefined local variable or method `cmd' for #<DEBUGGER__::Session:0x0000000120a0fa20>>
debug-1.10.0/lib/debug/session.rb:934:in `block in register_default_command'
debug-1.10.0/lib/debug/session.rb:1165:in `process_command'
...
```
...instead of this hint:
```
To evaluate the variable `eval`, use `pp eval` instead.
```
I believe the regression was introduced in a402e73.
To fix this issue, I was thinking of passing the command name alongside the argument in the `process_line` method but I wasn't sure this was worth it just for this hint. So I removed the hint altogether instead.
=> Fix help message of the `eval` command

lib/debug/console.rb
Fixes encoding crash when `LANG=` (empty) by using `String#scrub` to handle invalid characters gracefully.
When `LANG=`, debugger crashes with `Encoding::CompatibilityError` on history files with UTF-8 characters.
Use `String#scrub` to clean problematic characters instead of forcing UTF-8 encoding.
Fixes #1131
=> Fix encoding crash when LANG environment is empty

README.md, lib/debug/config.rb, lib/debug/console.rb
* Set default of `CONFIG[:history_file]` as nil, and ignore it if it is nil.
* Respect `CONFIG[:history_file]` even if the path doesn't exists.
* Respect `~/.rdbg_history` if exists for compatibility.
* Use `XDG_STATE_HOME` if there is no configuration about history file.
=> fix hitory file path

README.md, lib/debug/config.rb
Followup documentation/comments for #1146 
The RUBY_DEBUG_HISTORY_FILE has a default value of `$XDG_STATE_HOME/rdbg/history` which is already documented. However, the fallback value for the env variable `XDG_STATE_HOME` is not documented. Users who are unfamiliar with XDG basedir spec may not know that the default value for it is `~/.local/state/`.
This change uses bash parameter expansion syntax to "self-document" the fallback value for the variable when it is unset.
Note: I used the `-` default syntax, not the `:-` syntax. This is because the current ruby code does not check if `XDG_STATE_HOME` is _empty_, it merely checks if it is _set_. So an empty-string value would not trigger the fallback location to be used.
This PR was spawned from the following discussion: …
=> Self-document the XDG_STATE_HOME fallback

ext/debug/iseq_collector.c
The imemo mask has been `0xf` since Ruby 2.5 / [ccfe37884ab566336380d0f21e15321d6382da8f](https://github.com/ruby/ruby/commit/ccfe37884ab566336380d0f21e15321d6382da8f)
This hasn't caused problems yet because the only possible conflict is `imemo_type = 15`, but it is not yet used.
But this begs the question of how we can keep these two in sync, because `imemo_type = 15` is the last free imemo type, so the mask may be enlarged again soon.
=> Update imemo_mask to match ruby's
