ruby/debug

- CONTRIBUTING.md
- README.md
- misc/README.md.erb
Because this project still doesn't have test cases yet (coming in #9), I think we need to provide contributors some way to test their changes.
> Add CONTRIBUTING.md

- lib/debug/frame_info.rb
When experimenting different formats for #13, I found that splitting each component's (location, callee identifier and return value) string computation can reduce the overhead of switching between formats. We may even be able to allow users customize the format in the future.
**This doesn't change the output**.
```
❯ exe/rdbg -e 'b 20;; c ;; bt ;; info ;; q!' -e c target.rb
[1, 10] in target.rb
=>    1| class Foo
2|   def first_call
3|     second_call(20)
4|   end
5|
6|   def second_call(num)
7|     third_call_with_block do |ten|
8|       forth_call(num, ten)
9|     end
10|   end
=>#0    <main> at target.rb:1
(rdbg:init) b 20
#1 line bp /Users/st0012/projects/debug/target.rb:20 (return)
(rdbg:init) c
[15, 23] in target.rb
15|     yield(10)
16|   end
17|
18|   def forth_call(num1, num2) …
```
> Extract FrameInfo#to_client_output's component computation

- lib/debug/thread_client.rb
> Apply bold style to colors for readability with bright bg

- lib/debug/thread_client.rb
**Coloring Enabled**
**Coloring Disabled**
> Colorize info output

- README.md
- test/debug/bp_test.rb
- test/support/utils.rb
I decide not to add these changes in https://github.com/ruby/debug/pull/50 in case it's rejected or needs more time for review. This could be merged right away.
> Add binding bp test & update readme

- misc/README.md.erb
This is a follow up of https://github.com/ruby/debug/pull/52.
> Update readme template's badge too

- lib/debug/breakpoint.rb
- lib/debug/color.rb
- lib/debug/session.rb
- lib/debug/thread_client.rb
Closes https://github.com/ruby/debug/issues/59
Screenshot:
> Label breakpoint messages

- test/debug/break_test.rb
- test/debug/watch_test.rb
Just some description corrections plus removing a disabled test case.
> Minor improvements on tests

- test/debug/list_test.rb
This needs https://github.com/ruby/debug/pull/112 to work.
> Add list tests

- lib/debug/session.rb
- test/debug/break_test.rb
- test/debug/catch_test.rb
- test/debug/watch_test.rb
> Disable repetition on certain commands

- test/assertion_helper_test.rb
- test/debug/trace_test.rb
- test/support/assertions.rb
improve the regexp pattern in assert_line_text
> Improve assert line text method

- README.md
- lib/debug/session.rb
- lib/debug/thread_client.rb
- test/debug/backtrace_test.rb
> Support filtering in backtrace command

- test/support/utils.rb
```ruby
require_relative '../support/test_case'
module DEBUGGER__
class BindingBPWithCommandTest < TestCase
def program
<<~RUBY
1| at_exit{
2|   binding.bp
3|   eval('a = 1')
4|   Thread.new{}
5| }
6|
7| binding.bp(command: 'q!')
RUBY
end
def test_foo
debug_code(program) do
type 's'
type 'n'
end
end
end
end
```
Current test framework doesn't check if there are any errors in @last_backlog after `q!`.
```shell
$ RUBY_DEBUG_TEST_NO_REMOTE=1 ruby test/debug/foo_test.rb
Loaded suite test/debug/foo_test
Started
.
Finished in 0.560616 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- …
```
> Check if there are any errors in @last_backlog

- lib/debug/color.rb
- lib/debug/thread_client.rb
> Colorize pp command's output

- README.md
- misc/README.md.erb
> Fix small typo in the README

- CONTRIBUTING.md
Since we decided to keep the manual testing section in https://github.com/ruby/debug/pull/178, we should keep the expected result up-to-date.
> Update the expected manual testing result

- test/debug/config_test.rb
- `skip_path`
- `show_src_lines`
- `show_frames`
> Add tests for config options

- test/debug/quit_test.rb
The following codes based on byebug project.
> Add test cases for quit command

- README.md
- lib/debug/session.rb
- lib/debug/thread_client.rb
- lib/debug/tracer.rb
- test/debug/trace_test.rb
* `trace line`: line tracer
* `trace call`: call tracer
* `trace pass`: passing tracer
* `trace off`: disable a tracer
> `trace` command

- test/support/utils.rb
`$ RUBY_DEBUG_TEST_DISABLE_THREADS=1 rake test`
`$ rake test`
> Add the option to disable multi threaded test

- lib/debug/tracer.rb
This is my 100th PR of this project 🎉
> Simplify tracer's parameter processing

- lib/debug/tracer.rb
- test/debug/trace_test.rb
I also improved tracer's test cases.
> Fix NoMethodError when use trace raise with pattern

- CONTRIBUTING.md
There are some old informations for test builder. This pull request fix them to match the current format.
> Update the guide for test builder

- lib/debug/breakpoint.rb
- lib/debug/session.rb
- lib/debug/thread_client.rb
- test/debug/catch_test.rb
> Add do, pre, and if options to the catch command (#217)

- lib/debug/breakpoint.rb
- lib/debug/session.rb
Changes are explained in commit messages.
> Remove unused code

- README.md
- lib/debug/config.rb
- lib/debug/session.rb
- test/debug/config_test.rb
> Improve comments

- lib/debug/server_dap.rb
> Correct exception msg

- lib/debug/config.rb
- lib/debug/session.rb
- test/debug/config_test.rb
> LOG_LEVELS should be defined in config.rb

- misc/README.md.erb
Here is the PR requested by @ko1 on #266
> Update README.md.erb to match README.md

- lib/debug/session.rb
`bundle exec` doesn't use `exec` if the loading command is
written in Ruby. To check this kind of invocation, obnserving
`$0` modification and setup debugger.
`RUBY_DEBUG_INITIAL_SUSPEND_PATH` envval is provided for the this
purpose and maybe we shouldn't document it if we can find general
usage of it.
Fix #267
See #269
> skip loading on `bundle exec` 2nd approach

- lib/debug/config.rb
- lib/debug/session.rb
- test/debug/config_postmortem_test.rb
> Support activating postmortem mode with env var

- README.md
- misc/README.md.erb
> Fix typos in readme

- lib/debug/server_cdp.rb
Current CDP server doesn't support "Pause on exceptions" feature as follows(The icon on the far right):
This PR supports it.
> Support "Pause on exceptions" feature in CDP

- lib/debug/server_cdp.rb
> Fix bug that several types doesn't show their classes

- ext/debug/debug.c
- lib/debug/frame_info.rb
- lib/debug/thread_client.rb
- test/debug/debugger_local_test.rb
This is another fix of #424.
Tests are imported from #424 written by @st0012.
> Use same dupped binding while same sub-session

- lib/debug/thread_client.rb
> use `show_src_lines` config on `list` command

- lib/debug/server_cdp.rb
CDP has the issue of #431, too. This PR fixes it.
> Skip cleanup code for CDP

- lib/debug/server_cdp.rb
> Make sure to match all constant variables in Chrome

- debug.gemspec
Update the gemspec file to the latest bundler template.
> Exclude useless files from gem

- debug.gemspec
> Fix spelling in gem description

- test/support/dap_utils.rb
> Call "recv_request" method with correct number of arguments

- lib/debug/server_cdp.rb
> Set lineNumber of functionLocation correctly

- lib/debug/server_cdp.rb
- lib/debug/server_dap.rb
- test/dap/hover_test.rb
> Match not only top level namespaces but also inside of them

- debug.gemspec
https://github.com/rubygems/rubygems/issues/5255
> Don't install `bin` directory

- test/support/dap_utils.rb
The current DAP test framework already works great. But I think we can further improve it by by aligning its implementation with the debugger test framework:
- By storing `RemoteInfo` in the test info object like we do in other tests, we can reduce objects that need to be passed around.
- `response` and `event` types of messages are processed very similarly. So they can share some helpers.
- Renaming short variable names, like `k`, `v`, to `keys` and `expected_values` can make it more understandable.
This PR doesn't change any behavior of the DAP framework.
**Failure Example**
```
Failure: test_hover_works_correctly(DEBUGGER__::HoverTest1638791703):
-------------------------
| All Protocol Messages |
-------------------------
V>D …
```
> Refactor dap test utils

- README.md
- misc/README.md.erb
Hello! I noticed a rather odd sentence in the demonstration code in the README file, so I updated it.
(Feel free to close this PR if it's considered too little effort).
> Update odd sentence in readme demonstration code

- lib/debug/session.rb
Hello guys,
Colorize h[elp].
Write category with h[elp] using arguments the same way is already done with h[elp] without arguments.
Thank you very much.
> Improve help

- lib/debug/server_cdp.rb
> Set abbreviated property values in the Chrome DevTools Console

- lib/debug/server_cdp.rb
- lib/debug/session.rb
> Improve error messages in the Chrome DevTools Console

- lib/debug/server_cdp.rb
> Use file scheme instead of http scheme in Page pane

- lib/debug/server_cdp.rb
- Improve the way to convert messages to binary in WebSocketClient class
- Define "show_protocol" method
> Refactor the logic in WebSocket class

- test/debug/nested_break_test.rb
I forget to add this file with 4af8c25140a7a672db852954b6a1733b3169b608
> add a test file for nested breakpont

- lib/debug/session.rb
dirname can contain regexp meta characters.
> escape dirname in Regexp

- lib/debug/console.rb
Instead of adding `#ruby` on the right of input Ruby expressions,
this patch changes the prompt to the `ruby`.
This patch can relax issue about #538
> change prompt to `ruby` for ruby statements

- lib/debug/server.rb
- `GreetingError` retries accept
- add `info` sever request
> greeting error

- lib/debug/server_cdp.rb
- lib/debug/server_dap.rb
- lib/debug/session.rb
- lib/debug/thread_client.rb
These 2 commits were cherry-picked from #503, which I think are beneficial for future chagnes regardless if TUI is supported or not.
> Refactor Session and ThreadClient

- lib/debug/config.rb
- lib/debug/frame_info.rb
- lib/debug/thread_client.rb
- test/console/config_test.rb
See https://github.com/ruby/debug/pull/673#issuecomment-1174066633
> Address #673's feedback

- debug.gemspec
> reline v0.3.1

- exe/rdbg
- lib/debug/session.rb
- test/console/break_test.rb
- fix typo and add a test
- trap `BasicObject#singleton_method_added`
> fix user defined mthod add hooks

- ext/debug/extconf.rb
Clean up the generated file at `distclean`.
> Clean up "debug_version.h"

- lib/debug/server_dap.rb
Fixed typo  when raising error message on failed request.
> Fix typo on dap failed request

- lib/debug.rb
- lib/debug/prelude.rb
> skip if `RUBY_DEBUG_ENABLE=0`

- README.md
- lib/debug/session.rb
- lib/debug/thread_client.rb
- `whereami` command
- update doc
> whereami command

- test/console/whereami_test.rb
Add a simple test for the new `whereami` command.
> Add whereami test

- test/protocol/detach_raw_dap_test.rb
> Fix raw test case for detaching

- lib/debug/server_cdp.rb
https://user-images.githubusercontent.com/59436572/202905990-2c04953f-964f-4aa4-8c24-950a9a261932.mp4
> Support opening Chrome automatically on linux

- .github/workflows/ruby-macos.yaml
> Configure Github Actions to run console tests for macOS

- lib/debug/breakpoint.rb
- lib/debug/server.rb
- lib/debug/session.rb
WARN: should be known messages
INFO: informative messages
DEBUG: only for debug debug.gem
> fix log level

- lib/debug/client.rb
`Kernel#gets` read from ARGV if it is not empty.
> use `IO#gets`

- lib/debug/server_cdp.rb
https://user-images.githubusercontent.com/59436572/204118384-c0b81fd5-7f99-438c-b7fb-369d1f475470.mov
> CDP: Display the console when opening chrome automatically

- README.md
- lib/debug/abbrev_command.rb
- lib/debug/session.rb
- test/console/info_test.rb
* add `breakpoints`
* add `watchpoints`
* support abbrev subcommands
> extend `info` command

- lib/debug/server_cdp.rb
- lib/debug/server_dap.rb
- lib/debug/thread_client.rb
- test/console/info_test.rb
`const_get` can raise an error so it should be handled.
> take care exceptions from `const_get`

- Rakefile
https://github.com/ruby/debug/blob/d7bf3b2e4502eb0f07a67f00e5fce5a0d661189e/Rakefile#L52
> Correct `test_all` task command in Rakefile warning

- README.md
- misc/README.md.erb
> Fix typo in README

- lib/debug/server_cdp.rb
Close #800
https://user-images.githubusercontent.com/59436572/223464045-4f5a57d5-1292-4f9f-8946-5d0845c18637.mov
> CDP: Support reattaching in Chrome DevTools

- lib/debug/server_dap.rb
Reverts ruby/debug#935
will be merged on 1.8
> Revert "DAP: introduce Rdbg Record Inspector"

- lib/debug/server_dap.rb
- test/protocol/eval_test.rb
> DAP: echo back the given command

- lib/debug/server_cdp.rb
From investigation by @ko1-san, the path to set breakpoints seems to be sent in "url" field when debugging in different environment such as WSL(running debuggee) and Windows(running Chrome DevTools). I supported "url" field in this PR.
> CDP: support remote debugging in different environment

- lib/debug/server_dap.rb
and we can intercept each requests.
See https://github.com/ruby/debug/pull/931
> separate `process` with `process_request`

- README.md
- lib/debug/config.rb
- lib/debug/thread_client.rb
- test/console/config_test.rb
See https://github.com/ruby/debug/issues/881
> `no_lineno` config optiopn (default: false)

- lib/debug/config.rb
was introduced accidentally, maybe.
> remove debug print

- README.md
- misc/README.md.erb
> Minor punctuation and grammar fixes

- README.md
- lib/debug/session.rb
After #1024, the `irb` command does more than starting a pure IRB session.
> Correct the irb command's description
